### PR TITLE
Refactor cloud directory

### PR DESCRIPTION
**Pull request by Pokom**
## What does this PR change?
* Refactor `cloud` directory to create dedicated modules per CSP

## Does this PR relate to any other PRs?
* N\A

## How will this PR impact users?
* Ideally it won't

## Does this PR address any GitHub or Zendesk issues?
* #1788 

## How was this PR tested?
* Smoke Tests, Canary in Grafana Labs environment, E2E tests from Kubecost

## Does this PR require changes to documentation?
* No

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next Opencost release? If not, why not?
*

### CODE REVIEW

**Comment by nikovacevic** [comment]
Hi @Pokom thank you for your contribution. Can you help us understand why this change is beneficial and important?

**Comment by Pokom** [comment]
hey @nikovacevic, see this comment(https://github.com/opencost/opencost/issues/1788#issuecomment-1478717332) on the issue I linked to. I've working with @AjayTripathy on starting to do CloudCosts(S3 specifically) and this change is necessary to decouple the cloud providers.

**Comment by nikovacevic** [comment]
I see, thank you. Missed the linked issue.

**Comment by Pokom** [comment]
@Sean-Holcomb I'm going to close this PR in favor of issuing a new one. I'll refactor just AWS and test it out locally and then fire off a PR.

**Pull request closed without merging**
