### PR TITLE
Third party attributions in opencost artifacts

### PR DESCRIPTION
**Pull request by anders-swanson**
## What does this PR change?
* Add third party licenses, copyright information to the opencost artifacts.

## Does this PR relate to any other PRs?
* 

## How will this PR impact users?
* license and copyright information will be available for users in the opencost artifacts

## Does this PR address any GitHub or Zendesk issues?
* #2457 

## How was this PR tested?
* Built dockerfile, verified license file was present and readable.

## Does this PR require changes to documentation?
* N/A

### CODE REVIEW

**Comment by mattray** [comment]
@anders-swanson thanks for submitting this! 

Do we need to have it for the OpenCost UI container too?

Would it be possible to document how this was generated? Maybe we could add it to the https://github.com/opencost/opencost/blob/develop/CONTRIBUTING.md?

**Comment by anders-swanson** [comment]
> @anders-swanson thanks for submitting this!
> 
> Do we need to have it for the OpenCost UI container too?
> 
> Would it be possible to document how this was generated? Maybe we could add it to the https://github.com/opencost/opencost/blob/develop/CONTRIBUTING.md?

Thanks, I forgot about the UI container. It's been added there as well.

I also updated the contributing doc, let me know if that looks good!

**Review by mattray — APPROVED** [review]

**Comment by anders-swanson** [comment]
Running `just test` locally does not result in any test failures. Any ideas @mattray?

**Comment by mattray** [comment]
@anders-swanson your PR doesn't fail for me and I can't figure why it would fail on this commit, I'm merging.

**Pull request merged**
