### PR TITLE
Refactor and add testing for Athena and S3 row parsing

### PR DESCRIPTION
**Pull request by Sean-Holcomb**
## What does this PR change?
* This PR adds in test for the S3 and Athena integration. To do so the row parsing of the integrations is broken out into its own unit testable values. Additionally many of the strings that were previously in use I replaced with constants as well as standardizing existing constants.
* Fixes bug on S3 integration where amortized and net amortized costs were being swapped

## Does this PR relate to any other PRs?
* adds test coverage for https://github.com/opencost/opencost/pull/2896

## Does this PR address any GitHub or Zendesk issues?
* Closes ...

## How was this PR tested?
* Tested with unit tests

## Does this PR require changes to documentation?
* 

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next OpenCost release? If not, why not?
*

### CODE REVIEW

**Comment by ameijer** [comment]
@Sean-Holcomb LMK when you have test coverage and I will review!

**Comment by Sean-Holcomb** [comment]
@ameijer I am not sure what is going on with the quality gate here but I covered every line of code in the new functions. The rest of the code is not unit testable, which is the point of this PR.

**Comment by Sean-Holcomb** [comment]
@ameijer I have added test cases that give full coverage on the functions that I added so that this code could be tested. If you don't want to review as is I will remove the constants that I added and put back the literals that I replaced to make the quality gate pass

**Review by ameijer — APPROVED** [review]
LGTM

**Pull request merged**
