### PR TITLE
UI build fails with "Browser scripts cannot have imports or exports"

### PR DESCRIPTION
**Pull request by srpomeroy**
## What does this PR change?
* Adds module type to js import. Ref: https://github.com/parcel-bundler/parcel/discussions/6490

## Does this PR relate to any other PRs?
* No

## How will this PR impact users?
* It won't

## Does this PR address any GitHub or Zendesk issues?
* No

## How was this PR tested?
* Build is now successful

## Does this PR require changes to documentation?
* no

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next Kubecost release? If not, why not?
* Unsure if OSS UI is included in regular release cycle

### CODE REVIEW

**Comment by Adam-Stack-PM** [comment]
@teevans is OSS UI included in the regular release cycle?  See @srpomeroy PR note.

**Comment by dwbrown2** [comment]
@srpomeroy did you encounter with this install path or another? https://github.com/kubecost/opencost/blob/master/deploying-as-a-pod.md

**Comment by srpomeroy** [comment]
@dwbrown2 its from the simple UI deployment here: https://github.com/kubecost/opencost/blob/develop/ui/README.md

the parcel step.

**Comment by srpomeroy** [comment]
I meant to include this in the initial post.
image

**Review by nealormsbee — APPROVED** [review]
LGTM!

**Comment by nealormsbee** [comment]
The force push is because I thought that, in addition to the `type="module"` update, the API query path needed to be prefixed with `/model`.

So I made that update and was going to approve, but then realized that the prefix is only required because I'm running this against a closed-source backend. The FP was removing the commit that I had added to make that adjustment.

**Comment by dwbrown2** [comment]
Not sure I fully follow, more work needed here or should be all set?

**Comment by nealormsbee** [comment]
We're all set! I was just explaining the force push.

**Comment by srpomeroy** [comment]
Still not clear if this is part of any regular release cadence. Do I just merge and let @teevans figure it out?

**Comment by nealormsbee** [comment]
You can go ahead and merge this. If it needs to go into the release, we'll cherry-pick the commit into the `v1.94` branch. I think that would be the ideal, but is also unlikely to make a big impact.

We build images for the release, including an opencost image, but that image does not run the UI. The UI is for users grabbing the repo and running it locally. It would be *ideal* for the UI code at the `1.94.0` git tag not to be broken, but I strongly suspect users that want to run the UI are just pulling `develop` and running that.

Final call up to @teevans. I can create the cherrypick branch for this if there's time and inclination to get this into 1.94.0

**Comment by srpomeroy** [comment]
Thanks @nealormsbee !

**Pull request merged**
