### PR TITLE
fix transfer and receive queries for newer cadvisor

### LINKED ISSUE #1917: Missing "Data ingress" and "Data egress" B/s on `/abandoned-workloads`
**Describe the bug**

When on the `/abandoned-workloads` view, all statefulset workloads always report ‘Data ingress’ and ‘Data egress’ to have ‘0 B/s’ despite there being significant network traffic.

**To Reproduce**

1. Savings→’Remedy abandoned workloads’ report
1. Select Statefulset workload with known network activity
1. View ‘Data ingress’ and ‘Data egress’ in workload information

Compare this against the network costs of the same workload found on the ‘Allocations’ page and you will see there are network costs.

**Expected behavior**

For workloads that are known to have network activity, there should be reported X B/s for ‘Data ingress’ and ‘Data egress’. 

**Screenshots**

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-18) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by AjayTripathy**
## What does this PR change?
* Fixes issue where abandoned workloads would sometimes show 0 b/s in their data on certain versions of cadvisor

## Does this PR relate to any other PRs?
* No

## How will this PR impact users?
* 

## Does this PR address any GitHub or Zendesk issues?
* Closes https://github.com/kubecost/cost-analyzer-helm-chart/issues/1917

## How was this PR tested?
* Manually on http://ivan.kubecost.xyz

## Does this PR require changes to documentation?
* No

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next Opencost release? If not, why not?
* Yes, but we can also patch 101 potentially.

### CODE REVIEW

**Comment by nikovacevic** [comment]
@AjayTripathy I can approve this, but you need to sign the commit.

**Comment by nikovacevic** [comment]
Also @AjayTripathy can you write a sentence or two about why this fixes the issue? And has it just been broken for years?

**Comment by nikovacevic** [comment]
Also, if possible, can we try to rebase instead of merging develop into feature branches? Happy to help with that.

**Comment by nikovacevic** [comment]
Are we just reverting this? https://github.com/opencost/opencost/commit/b8bfe8e02284046e83c372c961fc97909df601db

If so, do we want to add `container!="POD"` back?

**Comment by nikovacevic** [comment]
According to @mbolt35 we do not need to add the other filter back. Happy to approve. We just need that commit sign-off.

**Review by nikovacevic — APPROVED** [review]

**Comment by AjayTripathy** [comment]
> https://github.com/opencost/opencost/commit/b8bfe8e02284046e83c372c961fc97909df601db

was a mistake that wasn't caught because old cadvisor still had data for this.

**Comment by nikovacevic** [comment]
FYI still cannot merge without signed commits

**Pull request merged**
