### PR TITLE
Run UI as USER 1001

### LINKED ISSUE #1824: Opencost-ui container uses root user.
**Is your feature request related to a problem? Please describe.**

Opencost-ui container is using root user. It poses some potential vectors for attack and best practices is to launch a container as a non-root user.

Some kubernetes clusters may be configured with a policy preventing such containers from starting. Opencost API container is using non-root user.

https://github.com/opencost/opencost/blob/develop/Dockerfile
https://github.com/opencost/opencost/blob/develop/ui/Dockerfile

### PR DESCRIPTION
**Pull request by AjayTripathy**
## What does this PR change?
* Run as user 1001

## Does this PR relate to any other PRs?
* No

## How will this PR impact users?
* Allows UI container to run as nonroot

## Does this PR address any GitHub or Zendesk issues?
* Closes https://github.com/opencost/opencost/issues/1824

## How was this PR tested?
* Will get tested by CI / CD building the container

## Does this PR require changes to documentation?
* No 

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next Opencost release? If not, why not?
* v103

### CODE REVIEW

**Comment by r2k1** [comment]
I think you need to set some extra permissions.

When I added this config to my opencost pod
```yaml
spec:
  securityContext:
    runAsUser: 1001
```

I got some permission errors writing to `/var/www`. Looked like some temporary files from nginx.

**Comment by JorgeGar** [comment]
Hi! I've been facing this issue also and I think there's more to it. I had to give ownership of `/var/www` and `/etc/nginx` to the user and that part worked, but the port binding fails. If I'm not mistaken the port should be changed to someone above 1024 to run as non root (maybe 8080).
```
running with BASE_URL=/model
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2023/05/19 06:24:58 [emerg] 1#1: bind() to 0.0.0.0:80 failed (13: Permission denied)
nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)
```

I hope it helps.

**Comment by JorgeGar** [comment]
> Unable to run UI "10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)" #1584

I found the solution. I have it running in my environment as non-root. If you are ok with it @AjayTripathy and @mattray, I can create a PR and propose the solution I found.

**Comment by jalev** [comment]
Just make the PR @JorgeGar; there hasn't been traction on this issue/pr for over a month and this is a problem now

**Comment by JorgeGar** [comment]
> Just make the PR @JorgeGar; there hasn't been traction on this issue/pr for over a month and this is a problem now

Here it goes: https://github.com/opencost/opencost/pull/1934

**Comment by mattray** [comment]
This was fixed in https://github.com/opencost/opencost/pull/1947

**Pull request closed without merging**
