### PR TITLE
update prometheus/client_golang

### PR DESCRIPTION
**Pull request by tomkukral**
Update prometheus client_golang to get better error messages.

Opencost is failing on my cluster with
```
 curl localhost:9003/metrics
An error has occurred while serving metrics:

17 error(s) occurred:
* duplicate label names
* duplicate label names
* duplicate label names
* duplicate label names
```

and new prometheus client should print which metric is duplicated.

## What does this PR change?
* bump prometheus/client_golang dependency

## How was this PR tested?
* not yet

## Does this PR require changes to documentation?
* no

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next OpenCost release? If not, why not?
*

### CODE REVIEW

**Comment by mattray** [comment]
Thanks for the PR, we're about to cut 1.107, but I'll try to get this into 1.108

**Comment by cliffcolvin** [comment]
@tomkukral if you'll resolve conflicts here I'll work to merge and test this

**Comment by tomkukral** [comment]
Thank you! Rebased.

**Comment by cliffcolvin** [comment]
@tomkukral I'm closing this PR as #2414 updated this library as well and is now merged. Please let me know if you have any issues or see another change we need to look at!

**Pull request closed without merging**
