### PR TITLE
Fix pod cache initialization

### PR DESCRIPTION
**Pull request by r2k1**
## What does this PR change?

Looks like due to the typo `podWatch` has been initialized twice and `poddisruptionbudgets` has not been initialized.

This caused requesting list of all pods during initialization.

### CODE REVIEW

**Review by mattray — APPROVED** [review]
@r2k1 thanks!

**Comment by worr** [comment]
@mattray Hey! Sorry to bother you, is there any chance that this will make it into the v1 line of releases? I see it's in several v2 releases

**Comment by mattray** [comment]
sorry for the confusion, the v2 releases are Kubecost's tags and unrelated to the v1.x series of OpenCost. We're sorting those out and this was committed to the `develop` branch, which will be branched soon for the `1.110.0` release

**Comment by worr** [comment]
Thanks for clearing up the confusion; looking forward to the next release.

**Pull request merged**
