### PR TITLE
[WIP] Add support for DefaultAzureCredentials

### PR DESCRIPTION
**Pull request by Davidsoff**
## What does this PR change?
* Add support for using [DefaultAzureCredentials](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#readme-defaultazurecredential) for azure blob authentication. This would remove the need for the creation of secrets in kubernetes. 
* Start using the blob provider from the [Azure SDK for Go](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go).

## Does this PR relate to any other PRs?
* Not as far as I'm aware

## How will this PR impact users?
* Allows use of [DefaultAzureCredentials](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#readme-defaultazurecredential) for authentication to blob storage.

## Does this PR address any GitHub or Zendesk issues?
* None, as far as I'm aware

## How was this PR tested?
* Unit tests ran successfully. Other than that I'll need some help on figuring out how the config is read, and if I need to change anything else to make it do what I expect it to do.

## Does this PR require changes to documentation?
* Yes, we'll need to let users know that OpenCost now supports DefaultAzureCredentials

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next OpenCost release? If not, why not?
* Not yet, this PR needs more work first

### CODE REVIEW

**Comment by AjayTripathy** [comment]
So cool! @kaelanspatel I know you were investigating some of this-- are you the right person to review or maybe @Sean-Holcomb ?

**Comment by mattray** [comment]
Thanks for submitting this PR! I'll raise it with Kubecost Engineering for review.

**Comment by Sean-Holcomb** [comment]
First impression is that this is a great contribution, the Azure authorizer is kind of the problem child of the CSP authorizers because it is the only interface that does not provide service agnostic. Ideally would be able to change the interface to be service agnostic too, but it would be challenging to do so without breaking existing users.

**Comment by Sean-Holcomb** [comment]
In terms of testing, one approach is to write an integration test like this https://github.com/opencost/opencost/blob/develop/pkg/cloud/azure/azurestorageintegration_test.go
pass criteria should be dependent on successful connection rather than contents of return. I would also want to build an image try both config methods.

**Comment by mattray** [comment]
@r2k1 @babbageclunk any feedback on this from the Azure side? Do we want to update this and get it merged?

**Comment by Sean-Holcomb** [comment]
@mattray I am working on some changes that we will allow us to merge this pr

**Comment by r2k1** [comment]
I would suggest taking a look at

https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#DefaultAzureCredential
https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#ChainedTokenCredential

**Comment by Sean-Holcomb** [comment]
Closing in favor of https://github.com/opencost/opencost/pull/2363 which includes the commit from this PR along with some structural updates and renaming.

**Pull request closed without merging**
