### PR TITLE
readme/screenshot update

### PR DESCRIPTION
**Pull request by jessegoodier**
## What does this PR change?
* clarify readme
* update UI screenshot

## Does this PR relate to any other PRs?
* no

## How will this PR impact users?
* improved clarity of readme

## Does this PR address any GitHub or Zendesk issues?
NA

## How was this PR tested?
Preview on github

## Does this PR require changes to documentation?
* No

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next Opencost release? If not, why not?
* just a readme update

### CODE REVIEW

**Review by mattray — APPROVED** [review]
Looks good to me. I'm submitting a PR shortly to add the OpenCost logo to the top of UI to distinguish it further from Kubecost. I'll re-refresh your image :)

**Review by AjayTripathy — APPROVED** [review]

**Comment by AjayTripathy** [comment]
@jessegoodier think you need to sign off on the DOC, you can do that here; https://github.com/opencost/opencost/pull/1520/checks?check_run_id=9898697554

**Comment by jessegoodier** [comment]
> @jessegoodier think you need to sign off on the DOC, you can do that here; https://github.com/opencost/opencost/pull/1520/checks?check_run_id=9898697554

thanks, not sure why all commits were not signed off, I used vscode for all of them.

done.

**Comment by mattray** [comment]
https://github.com/opencost/opencost/pull/1524

**Review by AjayTripathy — APPROVED** [review]

**Pull request merged**
