### PR TITLE
[UI]-Added the support for multiple currencies

### PR DESCRIPTION
**Pull request by saifullah619**
## What does this PR change?
* This PR is created to add the multiple currency support on the opencost's UI.

## Does this PR relate to any other PRs?
* No

## How will this PR impact users?
*  Currently only USD is supported and users can not change the currency from the UI. This PR contains the implementation to select the from multiple currencies.

## Does this PR address any GitHub or Zendesk issues?
* #1688 , #1800 

## How was this PR tested?
* Manually tested

## Does this PR require changes to documentation?
* Yes

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next Opencost release? If not, why not?
* Yes

### CODE REVIEW

**Comment by saifullah619** [comment]
Hey @mattray, Please review this PR and Merge this PR into develop

**Review by mattray — APPROVED** [review]
Looks great, thanks!

**Comment by mattray** [comment]
@saif-xgrid could you please do the DCO and we'll get it merged

**Comment by saif-xgrid** [comment]
> @saif-xgrid could you please do the DCO and we'll get it merged

@mattray Done

**Comment by majooneez** [comment]
Is it really provided in 1.104.0 release? I just pulled the new image - quay.io/kubecost1/opencost-ui:prod-1.104.0 but there is no dropdown menu for currency.

**Comment by csimplestring** [comment]
> Is it really provided in 1.104.0 release? I just pulled the new image - quay.io/kubecost1/opencost-ui:prod-1.104.0 but there is no dropdown menu for currency.

same here, we are using 1.104.2 but no dropdown for currency.

**Pull request merged**
