### PR TITLE
update prom queries to use more accurate math

### PR DESCRIPTION
**Pull request by nickcurie**
## What does this PR change?
* Fixes a bug with `queryLocalStorageUsedAvg` and `queryLocalStorageUsedMax` where they were averaging/maxing disk usage across disks instead of summing the usages of the disks on a node and then averaging/maxing them

## Does this PR relate to any other PRs?
* https://github.com/kubecost/cost-analyzer-helm-chart/pull/2590

## How will this PR impact users?
* Opencost/Kubecost have been incorrectly calculating cluster disk usage. Overall cost and capacity of Disks in the cluster are not affected, but features like and low disk right-sizing have been underestimating usage when making recommendations. We have fixed the calculation of usage, but incorrect sizing information may persist for up to a week after upgrading to a version of Opencost/Kubecost with the fix.

## Does this PR address any GitHub or Zendesk issues?
* Closes https://kubecost.atlassian.net/browse/GTM-86

## How was this PR tested?
* Tested on aws-test
  * Used the grafana pod in my namespace, exec'ed in and ran `df -h` to get the disk usage for the node, compared that value to the value given in prometheus from the query. Max query gave 7.121 GB, `df -h` reported 7.1 GB usage

## Does this PR require changes to documentation?
* 

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next OpenCost release? If not, why not?
* v1.107

### CODE REVIEW

**Comment by nickcurie** [comment]
@michaelmdresser I feel like my description of the issue is lacking a bit of detail. Any suggestions on how to make it more clear?

**Review by nik-kc — APPROVED** [review]

**Comment by michaelmdresser** [comment]
@nickcurie 
"Opencost/Kubecost have been incorrectly calculating cluster PV and disk _usage_. Overall cost and capacity of PVs and Disks in the cluster is not affected, but features like PV right-sizing and disk right-sizing have been underestimating usage when making recommendations. We have fixed the calculation of usage, but incorrect sizing information may persist for up to a week after upgrading to a version of Opencost/Kubecost with the fix."

Something like that makes a good release note. Sometimes a rebuild is recommended, but I think in this case the blast radius is small enough that we can just let the bad data roll off.

For fellow reviewers, a good comparison point is a PR like this https://github.com/opencost/opencost/pull/1813 which fixes the ingestion of a particular usage field which was previously incorrect.

**Review by michaelmdresser — APPROVED** [review]

**Comment by michaelmdresser** [comment]
EDIT: I was wrong about PVs -- we're still correct on PV stats

**Comment by AjayTripathy** [comment]
curious-- what was the uniqueness in metrics that was causing avg not to work? @nickcurie

**Comment by dwbrown2** [comment]
> curious-- what was the uniqueness in metrics that was causing avg not to work? @nickcurie

I believe it was metric duplication risk that caused us to use avg originally. @nickcurie any risk that you see for this?

**Comment by nickcurie** [comment]
@dwbrown2 this latest commit should address those risks, I've added back in an average to normalize those potential duplicated metrics.
@AjayTripathy after talking to @nikovacevic the average was likely used to normalize any jobs that may have duplicated metrics like Webb mentioned. Adding a `sum` here will actually give a total amount of disk space used rather than the average disk usage across disks that could vary significantly across them (i.e. 2TB, 1TB, and 500GB disks would give us an average of 1.67TB and not a real total of 3.5TB)

**Review by michaelmdresser — APPROVED** [review]

**Pull request merged**
