### PR TITLE
feat: add oci annotations to container images

### LINKED ISSUE #2132: Include OCI annotations in container images
**Is your feature request related to a problem? Please describe.**
A follow up to https://github.com/opencost/opencost/issues/1910.

Please make sure that containers being built have the proper [OCI annotations](https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys) added:

This can be added by the [docker-metadata](https://github.com/docker/metadata-action) action if you guys are using that.

**Describe the solution you'd like**
Making sure that tags like these are added to the image:
```
  org.opencontainers.image.created=2023-07-08T19:52:41.761Z
  org.opencontainers.image.description=reveal.js on steroids! Get beautiful reveal.js presentations from any Markdown file
  org.opencontainers.image.licenses=MIT
  org.opencontainers.image.revision=3fed7dbe6a05715a22edc3a03869b869b49b824a
  org.opencontainers.image.source=https://github.com/webpro/reveal-md
  org.opencontainers.image.title=reveal-md
  org.opencontainers.image.url=https://github.com/webpro/reveal-md
  org.opencontainers.image.version=5.5.1
```

**Describe alternatives you've considered**
N/A.

**Additional context**
The reason for why I want for you to add these, is that e.g. [Renovate Bot ](https://github.com/apps/renovate) is able to lookup `org.opencontainers.image.source` for where to look for the changelog to be included in a pull request.

I've replicated the behavior I like to see using some custom rules for Renovate Bot:

- Without changelog: https://github.com/MindTooth/renovate-opencost-test/pull/1
- With changelog: https://github.com/MindTooth/renovate-opencost-test/pull/2

### PR DESCRIPTION
**Pull request by MindTooth**
## What does this PR change?
The pull request adds OCI annotations.  Ref. #2132.

I tried to add them to the stages that produces the final image.

## Does this PR relate to any other PRs?
No.

However, if we were to use GitHub Actions using upstream Docker actions, these annotations could be automatic.  Ref. #1941.

## How will this PR impact users?
E.g. running Renovate Bot will know where to get it's changelog from.

## Does this PR address any GitHub or Zendesk issues?
Fix #2132.

## How was this PR tested?
I was able to build cost-model.  UI I had serious problems with locally on my Mac M1.

## Does this PR require changes to documentation?
No.

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next OpenCost release? If not, why not?
🤷🏻‍♂️

### CODE REVIEW

**Comment by MindTooth** [comment]
I tried my best to follow https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys and https://github.com/docker/metadata-action.  Feedback is appreciated.

**Review by mattray — APPROVED** [review]

**Comment by MindTooth** [comment]
@mattray just to ask, I can't see how you build images.  But are you guys using Docker actions? Maybe the metadata actions would be more suited?  I can help out with that as well.  Already migrated some projects I follow on GH.

**Comment by mattray** [comment]
@MindTooth there's a GitHub Action in a private repository that kicks off the Dockerfile.cross to build and generate the release artifact. I'd expect the labels to be applied after we merge this.

**Review by mattray — APPROVED** [review]

**Comment by MindTooth** [comment]
@mattray I think maybe we should apply this change:

```diff
- org.opencontainers.image.url=https://github.com/opencost/opencost
+ org.opencontainers.image.url=https://opencost.io
```

Feel that is more proper.  WYT?

**Comment by mattray** [comment]
I'm not really sure what the standards are for this. We are about to start publishing containers from https://github.com/opencost/opencost/pkgs/container/opencost, does that change anything?

**Comment by MindTooth** [comment]
I can't see the new code.  But if it does not alter labels by itself, we should be fine.

I'll submit a PR for the change.

**Pull request merged**
