### PR TITLE
feat: add export trigger endpoint

### PR DESCRIPTION
**Pull request by alileza**
## What does this PR change?
* It adds a new /export API to immediately trigger CSV export

## Does this PR relate to any other PRs?
nope

## How will this PR impact users?
* This will help new users test CSV export feature, checking integration & format, rather than waiting for the `00:10`

## Does this PR address any GitHub or Zendesk issues?
nope

## How was this PR tested?
deploy on dev env, `curl -X POST [pod]:9003/export` and see the CSV export logs 

## Does this PR require changes to documentation?
* Would be a nice addition to CSV export

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next OpenCost release? If not, why not?
*

### CODE REVIEW

**Comment by mattray** [comment]
@alileza this looks useful, thanks! I'll let @r2k1 comment on it since he provided the original CSV export functionality.

**Comment by r2k1** [comment]
I'm keen to know about the specific use-case you're addressing with this approach.

I think current export logic initiates data export at the application's start. Which, in my view, should adequately address the issue of feature testing.

On a side note. It would be nice to have an endpoint that returns the file in the response.

**Comment by alileza** [comment]
@r2k1 in my usecase its simply for testing purpose, since there's no way verify the CSV was uploaded to the the correct source (in my case S3), with which format, I'd have to wait for a day to gone by, just to see that there's an error on CSV processing.

**Comment by r2k1** [comment]
Changing configuration would require a pod restart. And a pod restart would trigger the export.
I didn't need to wait a day for testing. I would just restart the opencost pod.

Was it caused by something outside of opencost, like permissions misconfiguration in s3?

**Pull request closed without merging**
