### PR TITLE
example results from betteralign apply

### PR DESCRIPTION
**Pull request by saweber**
Not tested or intended to merge; currently an example.

Results are from: https://github.com/dkorunic/betteralign

This could be a significant opportunity to a fixed % reduction in memory consumption. Most notable would be reducing the memory footprint of allocations (328 bytes per allocation to 120 bytes). I have not investigated the side effects of running this. My primary concern would be  marshalling to storage and unmarshalling from storage - and there may be other concerns as well.

```
> betteralign -apply ./...
/home/steven/src/kubecost/opencost/pkg/log/counter.go:5:14: struct with 32 pointer bytes could be 8
/home/steven/src/kubecost/opencost/pkg/storage/azurestorage.go:69:18: struct with 272 pointer bytes could be 224
/home/steven/src/kubecost/opencost/pkg/storage/azurestorage.go:93:22: struct of size 144 could be 136
/home/steven/src/kubecost/opencost/pkg/storage/azurestorage.go:109:19: struct with 184 pointer bytes could be 176
/home/steven/src/kubecost/opencost/pkg/storage/gcsstorage.go:28:17: struct with 32 pointer bytes could be 24
/home/steven/src/kubecost/opencost/pkg/storage/s3storage.go:65:15: struct of size 360 could be 344
/home/steven/src/kubecost/opencost/pkg/storage/s3storage.go:99:19: struct with 136 pointer bytes could be 72
/home/steven/src/kubecost/opencost/pkg/storage/s3storage.go:160:16: struct with 48 pointer bytes could be 40
/home/steven/src/kubecost/opencost/pkg/storage/s3storage.go:590:14: struct with 112 pointer bytes could be 104
/home/steven/src/kubecost/opencost/pkg/storage/storage.go:18:18: struct with 48 pointer bytes could be 32
/home/steven/src/kubecost/opencost/pkg/util/atomic/atomicrunstate.go:9:21: struct with 32 pointer bytes could be 16
/home/steven/src/kubecost/opencost/pkg/config/configfile.go:55:17: struct with 152 pointer bytes could be 136
/home/steven/src/kubecost/opencost/pkg/config/configfile.go:360:15: struct with 24 pointer bytes could be 16
/home/steven/src/kubecost/opencost/pkg/cloud/models/models.go:41:11: struct with 328 pointer bytes could be 320
/home/steven/src/kubecost/opencost/pkg/cloud/models/models.go:75:23: struct with 104 pointer bytes could be 96
/home/steven/src/kubecost/opencost/pkg/cloud/models/models.go:88:9: struct with 104 pointer bytes could be 96
/home/steven/src/kubecost/opencost/pkg/cloud/models/models.go:113:29: struct with 64 pointer bytes could be 56
/home/steven/src/kubecost/opencost/pkg/cloud/models/models.go:246:20: struct with 32 pointer bytes could be 24
/home/steven/src/kubecost/opencost/pkg/cloud/models/models.go:265:27: struct with 16 pointer bytes could be 8
/home/steven/src/kubecost/opencost/pkg/cloud/models/serviceaccounts.go:10:27: struct with 32 pointer bytes could be 8
/home/steven/src/kubecost/opencost/pkg/cloud/models/serviceaccounts.go:41:26: struct with 32 pointer bytes could be 24
/home/steven/src/kubecost/opencost/pkg/util/timeutil/profile.go:56:19: struct with 40 pointer bytes could be 32
/home/steven/src/kubecost/opencost/pkg/clustercache/clusterexporter.go:37:22: struct with 64 pointer bytes could be 56
/home/steven/src/kubecost/opencost/pkg/clustercache/clusterimporter.go:18:22: struct with 40 pointer bytes could be 32
/home/steven/src/kubecost/opencost/pkg/clustercache/watchcontroller.go:43:29: struct with 96 pointer bytes could be 88
/home/steven/src/kubecost/opencost/pkg/filter21/ast/lexer.go:97:12: struct with 16 pointer bytes could be 8
/home/steven/src/kubecost/opencost/pkg/filter21/ast/lexer.go:106:14: struct with 80 pointer bytes could be 64
/home/steven/src/kubecost/opencost/pkg/filter21/ast/parser.go:44:13: struct with 48 pointer bytes could be 24
/home/steven/src/kubecost/opencost/pkg/filter21/matcher/stringmapmatcher.go:35:30: struct with 64 pointer bytes could be 56
/home/steven/src/kubecost/opencost/pkg/filter21/matcher/stringmatcher.go:35:27: struct with 64 pointer bytes could be 56
/home/steven/src/kubecost/opencost/pkg/filter21/matcher/stringslicematcher.go:36:32: struct with 64 pointer bytes could be 56
/home/steven/src/kubecost/opencost/pkg/collections/blockingqueue.go:39:32: struct with 40 pointer bytes could be 24
/home/steven/src/kubecost/opencost/pkg/util/stringutil/stringutil.go:26:17: struct with 16 pointer bytes could be 8
/home/steven/src/kubecost/opencost/pkg/util/httputil/roundtrip.go:5:25: struct with 32 pointer bytes could be 24
/home/steven/src/kubecost/opencost/pkg/prom/error.go:29:17: struct with 48 pointer bytes could be 40
/home/steven/src/kubecost/opencost/pkg/prom/error.go:86:26: struct with 56 pointer bytes could be 32
/home/steven/src/kubecost/opencost/pkg/prom/prom.go:116:34: struct with 88 pointer bytes could be 72
/home/steven/src/kubecost/opencost/pkg/prom/prom.go:212:18: struct with 88 pointer bytes could be 80
/home/steven/src/kubecost/opencost/pkg/prom/prom.go:225:19: struct with 48 pointer bytes could be 32
/home/steven/src/kubecost/opencost/pkg/prom/prom.go:347:29: struct with 64 pointer bytes could be 24
/home/steven/src/kubecost/opencost/pkg/prom/query.go:32:14: struct with 40 pointer bytes could be 32
/home/steven/src/kubecost/opencost/pkg/kubecost/allocation.go:54:17: struct with 328 pointer bytes could be 120
/home/steven/src/kubecost/opencost/pkg/kubecost/allocation.go:1105:35: struct of size 160 could be 144
/home/steven/src/kubecost/opencost/pkg/kubecost/allocation.go:2603:25: struct with 32 pointer bytes could be 24
/home/steven/src/kubecost/opencost/pkg/kubecost/allocation_json.go:13:21: struct with 400 pointer bytes could be 392
/home/steven/src/kubecost/opencost/pkg/kubecost/allocationmatcher.go:102:26: struct with 296 pointer bytes could be 288
/home/steven/src/kubecost/opencost/pkg/kubecost/allocationprops.go:94:27: struct with 184 pointer bytes could be 168
/home/steven/src/kubecost/opencost/pkg/kubecost/asset.go:1100:11: struct with 192 pointer bytes could be 160
/home/steven/src/kubecost/opencost/pkg/kubecost/asset.go:1764:11: struct with 200 pointer bytes could be 112
/home/steven/src/kubecost/opencost/pkg/kubecost/asset.go:3242:20: struct with 32 pointer bytes could be 24
/home/steven/src/kubecost/opencost/pkg/kubecost/asset.go:3793:23: struct with 16 pointer bytes could be 8
/home/steven/src/kubecost/opencost/pkg/kubecost/audit.go:267:15: struct with 88 pointer bytes could be 64
/home/steven/src/kubecost/opencost/pkg/kubecost/cloudcost.go:397:24: struct with 40 pointer bytes could be 24
/home/steven/src/kubecost/opencost/pkg/kubecost/cloudcostprops.go:90:26: struct with 104 pointer bytes could be 96
/home/steven/src/kubecost/opencost/pkg/kubecost/coverage.go:11:15: struct with 96 pointer bytes could be 88
/home/steven/src/kubecost/opencost/pkg/kubecost/etlrange.go:12:25: struct with 32 pointer bytes could be 8
/home/steven/src/kubecost/opencost/pkg/kubecost/query.go:38:29: struct of size 168 could be 152
/home/steven/src/kubecost/opencost/pkg/kubecost/query.go:72:24: struct of size 88 could be 72
/home/steven/src/kubecost/opencost/pkg/kubecost/query.go:86:29: struct of size 216 could be 208
/home/steven/src/kubecost/opencost/pkg/kubecost/query.go:95:23: struct with 152 pointer bytes could be 136
/home/steven/src/kubecost/opencost/pkg/kubecost/status.go:6:16: struct with 144 pointer bytes could be 128
/home/steven/src/kubecost/opencost/pkg/kubecost/status.go:19:22: struct with 72 pointer bytes could be 64
/home/steven/src/kubecost/opencost/pkg/kubecost/status.go:28:17: struct with 104 pointer bytes could be 96
/home/steven/src/kubecost/opencost/pkg/kubecost/status.go:39:18: struct with 48 pointer bytes could be 40
/home/steven/src/kubecost/opencost/pkg/kubecost/status.go:47:23: struct with 128 pointer bytes could be 112
/home/steven/src/kubecost/opencost/pkg/kubecost/status.go:58:27: struct with 128 pointer bytes could be 112
/home/steven/src/kubecost/opencost/pkg/kubecost/summaryallocation.go:24:24: struct with 72 pointer bytes could be 64
/home/steven/src/kubecost/opencost/pkg/kubecost/summaryallocation.go:362:27: struct with 64 pointer bytes could be 40
/home/steven/src/kubecost/opencost/pkg/kubecost/summaryallocation.go:1362:32: struct with 80 pointer bytes could be 40
/home/steven/src/kubecost/opencost/pkg/kubecost/summaryallocation_json.go:11:32: struct with 160 pointer bytes could be 152
/home/steven/src/kubecost/opencost/pkg/kubecost/summaryallocation_json.go:82:40: struct with 48 pointer bytes could be 24
/home/steven/src/kubecost/opencost/pkg/cloud/alibaba/boaconfiguration.go:11:23: struct with 48 pointer bytes could be 40
/home/steven/src/kubecost/opencost/pkg/cloud/alibaba/provider.go:174:18: struct with 120 pointer bytes could be 112
/home/steven/src/kubecost/opencost/pkg/cloud/alibaba/provider.go:203:28: struct with 96 pointer bytes could be 88
/home/steven/src/kubecost/opencost/pkg/cloud/alibaba/provider.go:278:28: struct of size 48 could be 40
/home/steven/src/kubecost/opencost/pkg/cloud/alibaba/provider.go:299:26: struct with 24 pointer bytes could be 16
/home/steven/src/kubecost/opencost/pkg/cloud/alibaba/provider.go:321:14: struct with 120 pointer bytes could be 88
/home/steven/src/kubecost/opencost/pkg/cloud/alibaba/provider.go:1053:12: struct of size 40 could be 32
/home/steven/src/kubecost/opencost/pkg/cloud/alibaba/provider.go:1165:11: struct with 96 pointer bytes could be 88
/home/steven/src/kubecost/opencost/pkg/cloud/alibaba/provider.go:1179:27: struct with 16 pointer bytes could be 8
/home/steven/src/kubecost/opencost/pkg/cloud/aws/athenaconfiguration.go:11:26: struct with 112 pointer bytes could be 104
/home/steven/src/kubecost/opencost/pkg/cloud/aws/athenaintegration.go:50:25: struct with 200 pointer bytes could be 192
/home/steven/src/kubecost/opencost/pkg/cloud/aws/provider.go:152:10: struct of size 488 could be 472
/home/steven/src/kubecost/opencost/pkg/cloud/aws/provider.go:260:19: struct with 40 pointer bytes could be 32
/home/steven/src/kubecost/opencost/pkg/cloud/aws/provider.go:291:22: struct with 104 pointer bytes could be 96
/home/steven/src/kubecost/opencost/pkg/cloud/aws/provider.go:1881:22: struct with 48 pointer bytes could be 40
/home/steven/src/kubecost/opencost/pkg/cloud/aws/provider.go:1975:13: struct with 48 pointer bytes could be 40
/home/steven/src/kubecost/opencost/pkg/cloud/aws/s3configuration.go:11:22: struct with 64 pointer bytes could be 56
/home/steven/src/kubecost/opencost/pkg/cloud/azure/billingexportparser.go:21:23: struct with 120 pointer bytes could be 112
/home/steven/src/kubecost/opencost/pkg/cloud/azure/billingexportparser.go:51:26: struct with 88 pointer bytes could be 8
/home/steven/src/kubecost/opencost/pkg/cloud/azure/pricesheetdownloader.go:23:27: struct with 88 pointer bytes could be 80
/home/steven/src/kubecost/opencost/pkg/cloud/azure/pricesheetdownloader.go:274:30: struct with 16 pointer bytes could be 8
/home/steven/src/kubecost/opencost/pkg/cloud/azure/provider.go:355:25: struct with 80 pointer bytes could be 72
/home/steven/src/kubecost/opencost/pkg/cloud/azure/provider.go:365:35: struct of size 280 could be 272
/home/steven/src/kubecost/opencost/pkg/cloud/azure/provider.go:395:12: struct of size 184 could be 176
/home/steven/src/kubecost/opencost/pkg/cloud/azure/provider.go:523:22: struct with 24 pointer bytes could be 16
/home/steven/src/kubecost/opencost/pkg/cloud/azure/storageconfiguration.go:10:27: struct with 96 pointer bytes could be 88
/home/steven/src/kubecost/opencost/pkg/cloud/gcp/bigqueryconfiguration.go:13:28: struct with 64 pointer bytes could be 56
/home/steven/src/kubecost/opencost/pkg/cloud/gcp/provider.go:94:10: struct with 240 pointer bytes could be 192
/home/steven/src/kubecost/opencost/pkg/cloud/gcp/provider.go:114:20: struct with 56 pointer bytes could be 48
/home/steven/src/kubecost/opencost/pkg/cloud/gcp/provider.go:121:28: struct with 32 pointer bytes could be 24
/home/steven/src/kubecost/opencost/pkg/cloud/gcp/provider.go:180:21: struct with 40 pointer bytes could be 32
/home/steven/src/kubecost/opencost/pkg/cloud/gcp/provider.go:570:17: struct with 136 pointer bytes could be 120
/home/steven/src/kubecost/opencost/pkg/cloud/gcp/provider.go:583:18: struct with 40 pointer bytes could be 32
/home/steven/src/kubecost/opencost/pkg/cloud/gcp/provider.go:591:24: struct with 72 pointer bytes could be 56
/home/steven/src/kubecost/opencost/pkg/cloud/gcp/provider.go:601:18: struct with 16 pointer bytes could be 8
/home/steven/src/kubecost/opencost/pkg/cloud/gcp/provider.go:1183:26: struct with 80 pointer bytes could be 64
/home/steven/src/kubecost/opencost/pkg/cloud/gcp/provider.go:1196:25: struct with 24 pointer bytes could be 8
/home/steven/src/kubecost/opencost/pkg/util/watcher/configwatchers.go:9:23: struct with 24 pointer bytes could be 16
/home/steven/src/kubecost/opencost/pkg/cloud/provider/customprovider.go:29:21: struct with 160 pointer bytes could be 128
/home/steven/src/kubecost/opencost/pkg/cloud/provider/customprovider.go:74:24: struct with 72 pointer bytes could be 64
/home/steven/src/kubecost/opencost/pkg/costmodel/clusters/clustermap.go:104:27: struct with 72 pointer bytes could be 48
/home/steven/src/kubecost/opencost/pkg/filemanager/filemanager.go:137:21: struct with 40 pointer bytes could be 32
/home/steven/src/kubecost/opencost/pkg/metrics/deploymentmetrics.go:59:34: struct with 104 pointer bytes could be 96
/home/steven/src/kubecost/opencost/pkg/metrics/events.go:6:29: struct with 32 pointer bytes could be 24
/home/steven/src/kubecost/opencost/pkg/metrics/nodemetrics.go:208:46: struct with 48 pointer bytes could be 40
/home/steven/src/kubecost/opencost/pkg/metrics/nodemetrics.go:254:43: struct with 48 pointer bytes could be 40
/home/steven/src/kubecost/opencost/pkg/metrics/nodemetrics.go:300:27: struct with 88 pointer bytes could be 80
/home/steven/src/kubecost/opencost/pkg/metrics/podmetrics.go:119:17: struct with 16 pointer bytes could be 8
/home/steven/src/kubecost/opencost/pkg/metrics/podmetrics.go:1007:25: struct with 96 pointer bytes could be 88
/home/steven/src/kubecost/opencost/pkg/metrics/pvmetrics.go:45:17: struct with 16 pointer bytes could be 8
/home/steven/src/kubecost/opencost/pkg/metrics/servicemetrics.go:59:34: struct with 104 pointer bytes could be 96
/home/steven/src/kubecost/opencost/pkg/metrics/statefulsetmetrics.go:58:35: struct with 104 pointer bytes could be 96
/home/steven/src/kubecost/opencost/pkg/services/clusters/boltdbstorage.go:8:27: struct with 32 pointer bytes could be 16
/home/steven/src/kubecost/opencost/pkg/services/clusters/clustermanager.go:38:25: struct with 48 pointer bytes could be 40
/home/steven/src/kubecost/opencost/pkg/services/clusters/clustermanager.go:46:24: struct with 56 pointer bytes could be 48
/home/steven/src/kubecost/opencost/pkg/services/clusters/clustersendpoints.go:15:19: struct with 40 pointer bytes could be 24
/home/steven/src/kubecost/opencost/pkg/services/services.go:27:26: struct with 16 pointer bytes could be 8
/home/steven/src/kubecost/opencost/pkg/costmodel/aggregation.go:47:18: struct with 592 pointer bytes could be 448
/home/steven/src/kubecost/opencost/pkg/costmodel/aggregation.go:132:25: struct with 24 pointer bytes could be 16
/home/steven/src/kubecost/opencost/pkg/costmodel/aggregation.go:138:21: struct with 32 pointer bytes could be 24
/home/steven/src/kubecost/opencost/pkg/costmodel/aggregation.go:254:25: struct with 96 pointer bytes could be 56
/home/steven/src/kubecost/opencost/pkg/costmodel/aggregation.go:1607:19: struct with 112 pointer bytes could be 104
/home/steven/src/kubecost/opencost/pkg/costmodel/aggregation.go:2288:12: struct with 16 pointer bytes could be 8
/home/steven/src/kubecost/opencost/pkg/costmodel/allocation_types.go:12:10: struct with 136 pointer bytes could be 128
/home/steven/src/kubecost/opencost/pkg/costmodel/allocation_types.go:81:10: struct with 120 pointer bytes could be 96
/home/steven/src/kubecost/opencost/pkg/costmodel/allocation_types.go:127:9: struct with 104 pointer bytes could be 88
/home/steven/src/kubecost/opencost/pkg/costmodel/allocation_types.go:210:13: struct with 56 pointer bytes could be 48
/home/steven/src/kubecost/opencost/pkg/costmodel/allocationnode.go:36:18: struct with 96 pointer bytes could be 56
/home/steven/src/kubecost/opencost/pkg/costmodel/cluster.go:49:19: struct with 104 pointer bytes could be 40
/home/steven/src/kubecost/opencost/pkg/costmodel/cluster.go:110:11: struct with 216 pointer bytes could be 176
/home/steven/src/kubecost/opencost/pkg/costmodel/cluster.go:478:11: struct with 240 pointer bytes could be 136
/home/steven/src/kubecost/opencost/pkg/costmodel/cluster.go:709:19: struct with 120 pointer bytes could be 104
/home/steven/src/kubecost/opencost/pkg/costmodel/costmodel.go:53:16: struct with 96 pointer bytes could be 80
/home/steven/src/kubecost/opencost/pkg/costmodel/costmodel.go:79:15: struct with 456 pointer bytes could be 448
/home/steven/src/kubecost/opencost/pkg/costmodel/costmodel.go:2339:32: struct with 104 pointer bytes could be 96
/home/steven/src/kubecost/opencost/pkg/costmodel/csv_export.go:167:17: struct with 24 pointer bytes could be 16
/home/steven/src/kubecost/opencost/pkg/costmodel/metrics.go:69:24: struct with 40 pointer bytes could be 32
/home/steven/src/kubecost/opencost/pkg/costmodel/router.go:84:15: struct with 240 pointer bytes could be 232
/home/steven/src/kubecost/opencost/pkg/costmodel/router.go:168:15: struct with 64 pointer bytes could be 56
/home/steven/src/kubecost/opencost/pkg/costmodel/router.go:1189:18: struct with 40 pointer bytes could be 32
/home/steven/src/kubecost/opencost/pkg/util/cache/cachegroup.go:20:31: struct with 48 pointer bytes could be 32
/home/steven/src/kubecost/opencost/pkg/util/worker/worker.go:54:28: struct with 48 pointer bytes could be 32
```

### CODE REVIEW

**Comment by michaelmdresser** [comment]
@mbolt35 you should have a look, this is neat. Does struct field ordering matter for bingen backwards-compatibility?

**Comment by mbolt35** [comment]
> @mbolt35 you should have a look, this is neat. Does struct field ordering matter for bingen backwards-compatibility?

@saweber @michaelmdresser 

I've looked at this before. We definitely have struct padding inefficiencies. However, field ordering matters for bingen, so you would need to omit applying this for any bingen structs, which unfortunately is where the bulk of the savings would be.

To be clear, this isn't all about backwards compatibility, it's core to how bingen encoding/decoding works. It uses a deterministic field ordering. Changing that in anyway not only breaks backwards compatibility with old versions, but also current versions. 

Unfortunately go didn't provide anyway to pack a struct internally, which blows my mind but I guess par for the course

**Comment by saweber** [comment]
@mbolt35 Thank you for the context, that is helpful, but also unsurprising.

It may be worth evaluating a migration path, but I/we would need to prove out a migration path and prove a VERY significant benefit first. 

Thank you for your time!

**Comment by mbolt35** [comment]
> @mbolt35 Thank you for the context, that is helpful, but also unsurprising.
> 
> It may be worth evaluating a migration path, but I/we would need to prove out a migration path and prove a VERY significant benefit first.
> 
> Thank you for your time!

@saweber I looked into heavy optimization of bingen data about 2-3 years ago, and perhaps to give you some potential paths to traverse (or avoid), here were some of the things I looked into:

### Byte Buffer Stack Allocations on Read/Write 
Ensuring that [ByteBuffer](https://github.com/opencost/opencost/blob/develop/pkg/util/buffer.go) was optimized for primitive writes by preventing the compiler from escaping small byte array allocations to the heap. This is mainly accomplished by not passing any stack allocated data to interface methods. The go std library `encoding/binary` package has `Read` and `Write` methods that are forced to make small heap allocations simply to encode primitive data due to interactions with `io.Reader` and `io.Writer` as well as `binary.ByteOrder` interfaces. One thing you'll notice in our `Buffer` type, we use a stack allocated byte array and do not pass any variables to interface methods. For reference, here is the go std lib `binary.go`:
* [Read](https://cs.opensource.google/go/go/+/refs/tags/go1.20.5:src/encoding/binary/binary.go;l=232)
* [Write](https://cs.opensource.google/go/go/+/refs/tags/go1.20.5:src/encoding/binary/binary.go;l=341)

Compared with the opencost `Buffer`:
* [Buffer.read](https://github.com/opencost/opencost/blob/b184f186e02168b722a53ec986b65cdd569c5189/pkg/util/buffer.go#L239)
* [Buffer.write](https://github.com/opencost/opencost/blob/b184f186e02168b722a53ec986b65cdd569c5189/pkg/util/buffer.go#L303)

Here are some benchmarks using identical (I think write tests) from Oct, 2020:
```
Buffer (using binary.Write/binary.Read)

BenchmarkAllocationSetRange_BinaryEncoding-12           4384        251331 ns/op      189089 B/op       7472 allocs/op
BenchmarkAllocationSetRange_BinaryEncoding-12           4510        269205 ns/op      191811 B/op       7472 allocs/op

----

Buffer (using stack alloc write/read)

BenchmarkAllocationSetRange_BinaryEncoding-12           4708        220291 ns/op      187962 B/op       5138 allocs/op
BenchmarkAllocationSetRange_BinaryEncoding-12           5193        237675 ns/op      191356 B/op       5138 allocs/op
```

Speed delta isn't much, but you can clearly see a delta in allocations. Due to the age of this benchmark, take this all with a grain of salt. The go compiler is worlds better than it was 2.5 years ago. I had a lot of tests surrounding "temporary" heap allocations, and while it was difficult to create enough pressure to show variance, I observed many occasions where the smaller heap allocations would cause the internal go runtime heap to expand much more quickly than with the stack allocated temporaries. 

The way we were able to determine if a stack alllocated variable was escaped to the heap was by using the following:
```
go build -gcflags='all=-m' . 2>&1 | grep "escapes"
```

### Wasteful String Data 
An overwhelming amount of the total ETL data are `string` instances. Despite go strings being "immutable" (it is possible to mutate using trickery, but not advisable), whenever you are decoding byte data into a string, go will allocate space for the new string. Turns out, that there were so many instances of repeat string data in our data structures, that we saved ~ 95% by implementing an atomic global string bank which simply stores instances of unique strings, and allows us to throw away string data and re-use an existing string if it's already been allocated (this is "safe" because go strings are "immutable"). We end up doing some hyper optimization with strings in the `Buffer` type here: https://github.com/opencost/opencost/blob/b184f186e02168b722a53ec986b65cdd569c5189/pkg/util/buffer.go#L390-L405

The comment explains it fairly well, but this actually allows us to cast a subset of the byte array to a string, use that string to check if an instance exists within the string bank before allocating. In other words, we don't have to allocate a new string, check to see if it exists in the bank, just to throw it away if it does exist.

NOTE: Yes, the stringbank is unbounded, but we have yet to run into a problem here. It's also easy to locate the footprint of the bank in a heap dump. Worst case scenario is that we eventually need to implement some LRU policy for the bank. 

The bingen encoding also uses a parent-type scoped stringtable to compress the resulting byte array and make decoding a bit faster. 

### Struct Padding (Investigation Only)
What you've stumbled on is possibly one of the more disappointing aspects/realizations. Early on, I made the decision to stick with deterministic non-indexed ordering for fields to simplify generation and save 2 bytes per field (assuming we used a `u16` as a field "index"). I think at the time, I naively thought most go struct fields would use 2-byte aligned boundaries or that go would auto pack struct layouts, but I honestly don't remember the specific reasons why I dismissed the idea. The only "negative" side-effect I am aware of, pertaining to struct packing is CPU cache line collisions that can happen (this is the case on many common architectures). 

If you find that this is a game changing optimization and want to further discuss a path to implementation, let me know. Would love to revisit if it makes sense to do so.

**Comment by saweber** [comment]
Closing this PR. It is not going to be the easy win I hoped for, and has significant customer implications.

Huge thanks to @mbolt35 for the thorough explanation!

**Pull request closed without merging**
