### PR TITLE
Revert "Oracle Cloud Infrastructure (OCI) Provider"

### PR DESCRIPTION
**Pull request by anders-swanson**
Reverts opencost/opencost#2367

### CODE REVIEW

**Review by mattray — APPROVED** [review]

**Comment by ChihweiLHBird** [comment]
What happened to the OCI provider?

**Comment by mattray** [comment]
@ChihweiLHBird the code was submitted while awaiting approval from Oracle's internal processes and they have requested https://github.com/opencost/opencost/issues/2457 be included with their support. We're working on clearing this up quickly.

**Comment by anders-swanson** [comment]
Closing this as the licensing concerns have been addressed

**Comment by mewzherder** [comment]
Hi @anders-swanson ! Thanks for your help. We noticed that Oracle is behind the demo environment on the website, yet we have failed to show thanks by adding Oracle as a contributor to our front page. https://opencost.io :D Would you be the right person to give us the appropriate logo? If you can, I'll add it. I created this issue (https://github.com/opencost/opencost-website/issues/402) If so, we can chat in that issue or please connect me with someone who could help. thx! :)

**Comment by ameijer** [comment]
@anders-swanson wanted to follow up here - can we add your logo to the site?

**Comment by anders-swanson** [comment]
@ameijer @mewzherder see: https://github.com/opencost/opencost-website/issues/402

**Pull request closed without merging**
