### PR TITLE
Specify units of some CustomPricing fields

### PR DESCRIPTION
**Pull request by michaelmdresser**
## What does this PR change?
* Units on CustomPricing are unclear. Clarifying in Slack and updating comments to reflect confirmation. https://kubecost.slack.com/archives/G01MN4R06MB/p1676670390413629

### CODE REVIEW

**Review by AjayTripathy — APPROVED** [review]

**Comment by michaelmdresser** [comment]
@AjayTripathy do you know the units for some/all of these fields? I at least need RAM before merging.

**Comment by AjayTripathy** [comment]
Gb/hr

**Comment by michaelmdresser** [comment]
GB or GiB?

**Comment by AjayTripathy** [comment]
uhmm 1024, sorry. so Gib.

**Comment by michaelmdresser** [comment]
Thanks Ajay!

**Pull request merged**
