### PR TITLE
Adding exception for Cloud Services meter subcategory

### LINKED ISSUE #2906: Opencost reports wrong price for AKS Cluster with a node of type D4as V5
**Describe the bug**
Opencost reports Windows pricing ($0.3560) for AKS nodes of type D4as V5 even though it's a Linux node.

**To Reproduce**
1. Create an AKS Cluster with a node of type D4as V5 in any region.
2. Install Opencost
3. execute `kubectl port-forward` command for opencost pod for 9003 port.
4. Access http://localhost:9003/metrics
5. find `node_total_hourly_cost` metric and check the value its reporting.

**Expected behavior**
node_total_hourly_cost for a node of instance type Standard_D4as_v5 should report a value of 0.1720

**Screenshots**
Screenshot 2024-09-04 at 8 30 03 PM

**Which version of OpenCost are you using?**
v1.109.0

**Additional context**
No

### PR DESCRIPTION
**Pull request by raghavendra-rafay**
For some instance types like D4as v5 opencost fetch Cloud Services price resulting in reporting more cost than expected. This happens because Cloud Services meter subcategory isn't ignored like Windows.

## What does this PR change?
* Add an extra condition to ignore Cloud Services subcategory while parsing Rate Card API reposne for Azure.

## Does this PR relate to any other PRs?
* NA

## How will this PR impact users?
* The users with nodes of D4as v5 instance types in their clusters will start seeing correct pricing.

## Does this PR address any GitHub or Zendesk issues?
* Closes https://github.com/opencost/opencost/issues/2906

## How was this PR tested?
* An AKS cluster is created with D4as v5 Node Pool. After this change, we have verified the node_total_hourly_cost metric at /metrics endpoint, and the value in metric matches the Linux pricing of D4as v5.

## Does this PR require changes to documentation?
* No

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next OpenCost release? If not, why not?
* Yes, Issue: https://github.com/opencost/opencost/issues/2906

### CODE REVIEW

**Comment by AjayTripathy** [comment]
Thanks for this PR @raghavendra-rafay ! Can we get this reviewed cc @cliffcolvin

**Review by Sean-Holcomb — APPROVED** [review]
Looks like a safe change

**Comment by Sean-Holcomb** [comment]
@raghavendra-rafay The PR looks good, can you sign the commit so that DCO passes and then we will be able to merge

**Comment by cliffcolvin** [comment]
@raghavendra-rafay just following up here, if you'll sign the commit, I'll get this merged.
```
To add your Signed-off-by line to every commit in this branch:

Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
In your local branch, run: git rebase HEAD~2 --signoff
Force push your changes to overwrite the branch: git push --force-with-lease origin azure-incorrect-pricing
```

**Review by ameijer — APPROVED** [review]
LGTM

**Comment by cliffcolvin** [comment]
@raghavendra-rafay please update this branch with develop and then tag me and I'll get this merged. 
I tried to update the branch for you, but downstream is locked. If you'll merge develop in I'll finish here! 
Thanks for the work on this.

**Comment by cliffcolvin** [comment]
@raghavendra-rafay any chance you can update with develop? I'll get this merged, if so.

**Pull request merged**
