### PR TITLE
pkg/costmodel: fix dropped errors

### PR DESCRIPTION
**Pull request by alrs**
This picks up 12 dropped `err` variables in the `promparser` code found in `pkg/costmodel`.

### CODE REVIEW

**Review by cliffcolvin — APPROVED** [review]
LGTM

**Review by cliffcolvin — DISMISSED** [review]
@alrs on second thought here I've been asking around as this functionally changes the result. I believe this is a breaking change as clusterID isn't a required label. In the handled error case of this PR this will actually break when no clusterID is present. ClusterID being unset is an expected scenario for non-thanos (reading from local prom), and defaults to local cluster in that case.

**Comment by cliffcolvin** [comment]
I think the best route forward would be to comment/doc this expected behavior and _ out the err returns.

**Comment by alrs** [comment]
@cliffcolvin I've made the requested changes.

**Comment by alrs** [comment]
@mattray @cliffcolvin any word?

**Review by nikovacevic — APPROVED** [review]

**Review by cliffcolvin — APPROVED** [review]

**Pull request merged**
