### PR TITLE
feat: watch metrics-config in agent mode

### PR DESCRIPTION
**Pull request by antoinedeschenes**
Reopening #1899 

## What does this PR change?
* Allows agent mode to watch the metrics-config ConfigMap, this was unexpected as the costmodel execution behaves correctly. Documentation doesn't mention agent mode missing that feature.

## Does this PR relate to any other PRs?
* #1897 indirectly, we're trying to disable a few metrics in agent mode and having issues

## How will this PR impact users?
* Enables disabledMetrics support in agent mode

## Does this PR address any GitHub or Zendesk issues?
* Closes ...

## How was this PR tested?
Running locally port-forwarded to a remote cluster and Prometheus, with a provisioned metrics-config configmap.
* Log outputs:
   ```
   INF Starting metrics init with disabled metrics: [service_selector_labels statefulSet_match_labels 
   deployment_match_labels kube_namespace_labels kube_node_labels kube_pod_labels]
   ```
* `curl localhost:9005/metrics` output doesn't contain the above metrics once this PR is applied.

## Does this PR require changes to documentation?
* No, there are no mentions of the missing feature in agent mode.

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next Opencost release? If not, why not?
*

### CODE REVIEW

**Comment by AjayTripathy** [comment]
@mbolt35 is this something that makes sense for agentmode?

**Comment by AjayTripathy** [comment]
@nikovacevic actually since Bolt is out

**Comment by nikovacevic** [comment]
@AjayTripathy will try to get to it this week

**Comment by mattray** [comment]
Assigning to Kubecost Engineering for review

**Comment by nikovacevic** [comment]
Apologies, I did not get to this, obviously. @mbolt35 is back -- Bolt, do you want to sync on this, and decide together whether or not this makes sense?

**Pull request closed without merging**
