### PR TITLE
Swap `DCGM_FI_DEV_GPU_UTIL` for `DCGM_FI_PROF_GR_ENGINE_ACTIVE`.

### PR DESCRIPTION
**Pull request by thomasvn**
## What does this PR change?
* Swaps `DCGM_FI_DEV_GPU_UTIL` for `DCGM_FI_PROF_GR_ENGINE_ACTIVE` when calculating `gpuUsageAverage`
* This new metric provides higher precision, as well as support for MIG ([ref1](https://github.com/NVIDIA/DCGM/issues/64#issuecomment-1400811885), [ref2](https://github.com/NVIDIA/DCGM/issues/80#issuecomment-1537603016))

## Does this PR relate to any other PRs?
* Amends https://github.com/opencost/opencost/pull/2731

## How will this PR impact users?
* As stated above.

## Does this PR address any GitHub or Zendesk issues?
* Closes [ENG-2454](https://kubecost.atlassian.net/browse/ENG-2454)

## How was this PR tested?

Deployed a dummy workload onto a GPU node. Port-forwarding into Prometheus shows the `DCGM_FI_PROF_GR_ENGINE_ACTIVE` metric:

Screenshot 2024-07-29 at 1 12 39 PM

Ran cost-model locally, pointed at this Prometheus. Ran the query `http://localhost:9003/allocation?window=1h&aggregate=node` and saw the following `gpuRequestAverage` and `gpuUsageAverage` result:

<details>

<summary> Allocations API aggregated by node </summary>

```json
{
    "code": 200,
    "status": "success",
    "data": [
        {
            "ip-192-168-65-200.us-east-2.compute.internal": {
                "name": "ip-192-168-65-200.us-east-2.compute.internal",
                "properties": {
                    "cluster": "cluster-localrun-default",
                    "node": "ip-192-168-65-200.us-east-2.compute.internal",
                    "providerID": "i-03b8cc1c7f8cbe5d0"
                },
                "window": {
                    "start": "2024-07-29T20:00:00Z",
                    "end": "2024-07-29T21:00:00Z"
                },
                "start": "2024-07-29T20:00:00Z",
                "end": "2024-07-29T20:20:00Z",
                "minutes": 20,
                "cpuCores": 0.92533,
                "cpuCoreRequestAverage": 0.7195,
                "cpuCoreUsageAverage": 0.04444,
                "cpuCoreHours": 0.30844,
                "cpuCost": 0.0268,
                "cpuCostAdjustment": 0,
                "cpuCostIdle": 0,
                "cpuEfficiency": 0.06176,
                "gpuCount": 1,
                "gpuRequestAverage": 1,
                "gpuUsageAverage": 0.99593,
                "gpuHours": 0.33333,
                "gpuCost": 0.87037,
                "gpuCostAdjustment": 0,
                "gpuCostIdle": 0,
                "gpuEfficiency": 0.99593,
                "networkTransferBytes": 413349714.48649,
                "networkReceiveBytes": 294190194.87606,
                "networkCost": 0,
                "networkCrossZoneCost": 0,
                "networkCrossRegionCost": 0,
                "networkInternetCost": 0,
                "networkCostAdjustment": 0,
                "loadBalancerCost": 0,
                "loadBalancerCostAdjustment": 0,
                "pvBytes": 68719476736,
                "pvByteHours": 22906492245.33333,
                "pvCost": 0.00292,
                "pvs": {
                    "cluster=cluster-localrun-default:name=pvc-e6174ee9-de43-4667-bee0-c80d292eaea6": {
                        "byteHours": 11453246122.666666,
                        "cost": 0.0014611872146118722,
                        "providerID": "",
                        "adjustment": 0
                    },
                    "cluster=cluster-localrun-default:name=pvc-f26c280b-260d-45c4-a97d-3e2124f00ed2": {
                        "byteHours": 11453246122.666666,
                        "cost": 0.0014611872146118722,
                        "providerID": "",
                        "adjustment": 0
                    }
                },
                "pvCostAdjustment": 0,
                "ramBytes": 3175010816,
                "ramByteRequestAverage": 1443364864,
                "ramByteUsageAverage": 2035719810.32727,
                "ramByteHours": 1058336938.66667,
                "ramCost": 0.01148,
                "ramCostAdjustment": 0,
                "ramCostIdle": 0,
                "ramEfficiency": 1.4104,
                "externalCost": 0,
                "sharedCost": 0,
                "totalCost": 0.91157,
                "totalEfficiency": 0.4662,
                "lbAllocations": null
            }
        }
    ]
}
```

</details>

## Does this PR require changes to documentation?
* TODO

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next OpenCost release? If not, why not?
* v2.4

### CODE REVIEW

**Comment by AjayTripathy** [comment]
@thomasvn should we potentially be collecting both?

**Comment by thomasvn** [comment]
@AjayTripathy I think there are few advantages to collecting both. Instead we should try to build confidence that `DCGM_FI_PROF_GR_ENGINE_ACTIVE` is the right metric to be collecting and keying on. We can discuss more in a call if you'd like!

@chipzoller Let me know if you have any thoughts here as well.

**Comment by chipzoller** [comment]
From all information available, it sounds like we do not need to collect both.

**Comment by thomasvn** [comment]
@AjayTripathy Let me know what you think of this change! I'd like to test in our nightly environments as soon as possible.

**Comment by AjayTripathy** [comment]
I'm good with collecting both but we'd need a new field or schema right?

**Comment by thomasvn** [comment]
@AjayTripathy Sorry about my confusion here. Chip and I believe we _do not_ need to collect both. Is that ok with you?

**Comment by chipzoller** [comment]
Confirmed with a DCGM product manager last week that DCGM_FI_PROF_GR_ENGINE_ACTIVE is what we should be reading.

**Comment by thomasvn** [comment]
Thanks for the confirmation! @AjayTripathy @cliffcolvin Could I get a final review on this please?

**Review by ameijer — APPROVED** [review]

**Review by nikovacevic — APPROVED** [review]

**Pull request merged**
