### PR TITLE
Partially handle Azure Virtual Nodes (serverless)

### LINKED ISSUE #2109: Fix Azure virtual nodes cost
**Describe the bug**  
[Azure virtual node](https://learn.microsoft.com/en-us/azure/aks/virtual-nodes) cost is incorrect. 

**Reported**

**To Reproduce**  
1. Create a new AKS cluster with enable virtual nodepools
2. Check virtual node cost in Kubecost
3. Check virtual node cost in Azure

*Test Cluster*
`az aks get-credentials --resource-group ivanresourcegroup --name Ivan`

**Expected behavior**  
Kubecost displays the correct cost for Azure virtual nodes

**Screenshots**  
Screenshot 2023-04-04 at 2 10 32 PM
Screenshot 2023-04-04 at 2 14 16 PM

**Please share the support case, if any**  
https://kubecost.zendesk.com/agent/tickets/3702

### PR DESCRIPTION
**Pull request by thomasvn**
## What does this PR change?
* When using [Azure Virtual Nodes](https://learn.microsoft.com/en-us/azure/aks/virtual-nodes) (serverless), there is a node created `virtual-node-aci-linux`.
* According to the k8s API, this node has 10000 vCPU cores and 4096 GiB memory, however Azure does not charge for this node as a typical "Microsft.Compute". Instead, pods scheduled to `virtual-node-aci-linux` will get charged for execution hours as "Microsoft.ContainerInstance".
* This PR takes a first step in addressing Azure Virtual Nodes, by setting the cost of the `virtual-node-aci-linux` to $0.
* Work is still needed to ensure pods scheduled to `virtual-node-aci-linux` get proper cost allocations.

<details>

<summary> Example of how to schedule a pod onto a virtual node: </summary> 

```yaml
# Place this in the pod spec
tolerations:
- key: virtual-kubelet.io/provider
  operator: Exists
- key: azure.com/aci
  effect: NoSchedule
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
      - key: type
        operator: In
        values:
        - virtual-kubelet
```

</details>

## Does this PR relate to any other PRs?
* No

## How will this PR impact users?
* Users who are leveraging Azure's serverless option (Virtual Nodes) will no longer see costs associated with the virtual node.

## Does this PR address any GitHub or Zendesk issues?
* Closes https://github.com/kubecost/cost-analyzer-helm-chart/issues/2109

## How was this PR tested?
* Set up Prometheus on an AKS cluster with Virtual Nodes. Run OpenCost/Kubecost locally pointing at the remote Prometheus. Check http://localhost:9003/metrics to ensure that the following metrics have been zero'd out: `node_cpu_hourly_cost`, `node_ram_hourly_cost`, `node_total_hourly_cost`.
* Build a OpenCost/Kubecost image, then deploy to an AKS cluster with Virtual Nodes. Ensure that the node `virtual-node-aci-linux` has $0 in costs on the Assets view.

## Does this PR require changes to documentation?
* No

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next Opencost release? If not, why not?
*

### CODE REVIEW

**Comment by jessegoodier** [comment]
What is the expected behavior if a container is scheduled on a virtual node?
Would the costs be accurate?

**Comment by dwbrown2** [comment]
@thomasvn @AjayTripathy do you know how the scenario jesse mentioned would be handled?

**Comment by thomasvn** [comment]
@jessegoodier @dwbrown2 The current expected behavior is for the `/asset/node/virtual-node-aci-linux` to be $0, which is correct. However if a pod gets scheduled onto `virtual-node-aci-linux`, I expect its allocated costs to also be $0 which is not yet correct.

I’ll update the PR’s description to reflect this!

Potential solutions to ensure pods are correctly allocated costs:

- Apply a configurable default pricing to pods which are detected to be running on serverless (Azure Container Instances)
- Add logic to reconcile against the “Microsoft.ContainerInstance” line items in the Azure Billing Data.

**Review by AjayTripathy — APPROVED** [review]

**Comment by AjayTripathy** [comment]
Thanks @thomasvn ! Let's get this merged and if we can cherry picked into the 1.103 fix?

**Comment by AjayTripathy** [comment]
> I expect its allocated costs to also be $0 which is not yet correct.

The allocated costs would not be 0. They would be based on default pricing for now. We'd need to make them accurate when reconciliation data comes in, similar to how fargate works. But, let's get this in for now.

**Pull request merged**
