### PR TITLE
Draft: Remove CircleCI related files

### PR DESCRIPTION
**Pull request by wilsonwu**
## What does this PR change?
* Update later

## Does this PR relate to any other PRs?
* No

## How will this PR impact users?
* No

## Does this PR address any GitHub or Zendesk issues?
* No

## How was this PR tested?
* Update later

## Does this PR require changes to documentation?
* No

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next Opencost release? If not, why not?
* Update later

### CODE REVIEW

**Comment by wilsonwu** [comment]
@AjayTripathy Hi Ajay, could you please help to review this? Or anyone else I can reach, thank you!

**Comment by mattray** [comment]
Checking to see if we're still using CircleCI. I thought everything had been switched over to GitHub Actions.

**Comment by wilsonwu** [comment]
> Checking to see if we're still using CircleCI. I thought everything had been switched over to GitHub Actions.

Thanks for this info to me, I can also contribute the github action, shell we delete the circleci files?

**Comment by mattray** [comment]
@wilsonwu yeah, we definitely use GitHub Actions if you want to work in the `.github` directory. I'm still trying to get a definitive "no we don't use CircleCI", but nobody has said "yes" either. I'll leave this open until I have a definitive answer.

**Comment by wilsonwu** [comment]
@mattray Got it, I think you can set a deadline, if nobody say "yes", we can remove circleci related files :), let's keep this PR here for removal later if need, I will start new PR to let github action support arm64 docker image.

**Comment by mattray** [comment]
@wilsonwu agreed.

FWIW I run Arm64 on-prem and never have any issues with OpenCost.

**Comment by mattray** [comment]
Opened https://github.com/opencost/opencost/pull/1797 to track this

**Comment by wilsonwu** [comment]
@mattray the new PR here: #1799, please help to review.

**Comment by mattray** [comment]
Closing now that CircleCI has been removed.

**Pull request closed without merging**
