### PR TITLE
fix bugs referred by issue

### PR DESCRIPTION
**Pull request by wujunwei**
Signed-off-by: wujunwei <wjw3323@live.com>

## What does this PR change?
fix bugs reference by issue #1664

## Does this PR relate to any other PRs?
No

## How will this PR impact users?
No

## Does this PR address any GitHub or Zendesk issues?
#1664

## How was this PR tested?
YES

## Does this PR require changes to documentation?
NO

### CODE REVIEW

**Comment by thomasvn** [comment]
This looks good to me, @AjayTripathy ?

**Comment by AjayTripathy** [comment]
Everything lgtm but not sure about the change to *Window. @nikovacevic would be the expert there wdyt?

**Comment by nikovacevic** [comment]
Definitely a bug, yes, but I'd actually prefer to fix it by deleting the function and the two calls. (That function is only called in deprecated code, and already does nothing, so no harm in deleting it.)

Or an alternative would be to replace
```go
window.Set(&s, &e)
```
with
```go
window = kubecost.NewWindow(&s, &e)
```

The only two references to that function are here: https://github.com/opencost/opencost/blob/develop/pkg/costmodel/aggregation.go

**Comment by AjayTripathy** [comment]
I'm going to go ahead and approve this since removal is probably beyond the scope of an open source contribution and we can evaluate removal later!

Can we file an issue to remove later?

**Review by AjayTripathy — APPROVED** [review]

**Comment by nikovacevic** [comment]
I'll just make the changes later today.

**Pull request merged**
