### PR TITLE
Update S3 Storage Implementation

### PR DESCRIPTION
**Pull request by mbolt35**
## What does this PR change?
* Updates the S3 storage implementation to the latest thanos configuration specification. 

## How does this PR impact users? (This is the kind of thing that goes in release notes!)
* Updates the configuration for our S3 storage implementation to match the latest Thanos Configuration: https://thanos.io/tip/thanos/storage.md/#s3

## Links to Issues or ZD tickets this PR addresses or fixes
- https://github.com/kubecost/cost-analyzer-helm-chart/issues/1250

### CODE REVIEW

**Comment by AjayTripathy** [comment]
Could you note how this was tested?

**Comment by mbolt35** [comment]
@AjayTripathy This is a PR to bring the implementation to spec with Thanos. How would you propose we test that?

**Comment by AjayTripathy** [comment]
The specific issue here was that eks annotations weren't working when the same key config was applied to Thanos as to kubecost cost-model right? So I would propose we set a cluster up configured that way and note that we can save the etl.

**Comment by AjayTripathy** [comment]
We have a cluster set up now, so approving and we can look at the nightly.

**Review by AjayTripathy — APPROVED** [review]

**Pull request merged**
