### PR TITLE
Set up opencost UI image

### PR DESCRIPTION
**Pull request by biancaburtoiu**
## What does this PR change?
Set up Opencost UI image and Nginx setup; link into pod definition

## Does this PR relate to any other PRs?
No

## How will this PR impact users?
TBD 

## Does this PR address any GitHub or Zendesk issues?
TBD

## How was this PR tested?
TBD

## Does this PR require changes to documentation?
TBD

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next Opencost release? If not, why not?
*

### CODE REVIEW

**Comment by mattray** [comment]
@biancaburtoiu what do we need to do to help move this along? I've suggested closing #1393 in favor of this issue. I've also noted in #1518 that we should probably publish this out of the `kubecost` repository eventually. And finally, the opencost-ui build appears to be currently broken #1519.

Ideally someone who knows what they're doing can fix #1519 and we can get the `opencost-ui` published next to `kubecost-cost-model` in quay.io for now.

**Comment by biancaburtoiu** [comment]
Hi @mattray! The order of actions here should be as follows: (@nealormsbee, please correct me if I'm wrong here)
- Fix Dockerfile build error in #1519 
- Set up commands to build the ui/Dockerfile image as part of our release scripts. I have a WIP PR here https://github.com/kubecost/release-scripts/pull/31
- Modify opencost deployment spec to include the new UI container

I'll send more updates here as I get each of these items ironed out.

**Comment by biancaburtoiu** [comment]
I've closed this unintentionally as I was cleaning up my fork branch and can't seem to be able to reopen. WIP; should reopen once I commit the updated opencost deployment spec here

**Comment by biancaburtoiu** [comment]
I couldn't bring this branch back, please refer to the following links for all PRs related to this issue:
- https://github.com/opencost/opencost/pull/1527
- https://github.com/kubecost/release-scripts/pull/31
- https://github.com/opencost/opencost-website/pull/64

**Pull request closed without merging**
