### PR TITLE
docs-update/README.md

### PR DESCRIPTION
**Pull request by 0Armaan025**
## What does this PR change?
It updates README.md.

## Does this PR relate to any other PRs?

nope.

## How will this PR impact users?

This has made README.md more fun and engaging, which would potentially allow more users to contribute.

## Does this PR address any GitHub or Zendesk issues?
ig no!

## How was this PR tested?
yes, it works fine!

## Does this PR require changes to documentation?
yes, to README.md

Thanks and regards,
Armaan.

### CODE REVIEW

**Comment by mattray** [comment]
Thanks, I definitely like fun and engaging.

**Comment by 0Armaan025** [comment]
thank you so much!

**Comment by mattray** [comment]
It looks like you've got a pattern of contributing similar patches to dozens of projects.

**Comment by 0Armaan025** [comment]
Apologies for the confusion!

**Pull request closed without merging**
