### PR TITLE
added a separate client for prometheus scrape config endpoint

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**
## What does this PR change?
Adds a separate Prometheus client configuration for scrape config endpoint with the same env variables as for Prometheus server client, but prefixed with `SCRAPE_` for cases when `/status/config` and `/query` (or `/query_range`) endpoints are on different addresses (like in Victoria Metrics architecture)

## Does this PR relate to any other PRs?
#1430 

## How will this PR impact users?
it will not impact current behaviour till `SCRAPE_PROMETHEUS_SERVER_ENDPOINT` is set. With `SCRAPE_PROMETHEUS_SERVER_ENDPOINT` there will be a separate client to query scrape config (or any other information from a local prometheus (or VMAgent) instance)

## Does this PR address any GitHub or Zendesk issues?
* #1860 

## How was this PR tested?
* Tested it together with #1430 changes on my EKS setup with and without `SCRAPE_PROMETHEUS_SERVER_ENDPOINT` 

## Does this PR require changes to documentation?
* It's needed to add a section for scrape endpoint configuration

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next Opencost release? If not, why not?
* Have no permissions to label

### CODE REVIEW

**Comment by AndrewChubatiuk** [comment]
@mattray could you also review this in addition to #1430? It's also required to support Victoria Metrics

**Comment by mattray** [comment]
I'm going to defer to @AjayTripathy or someone else from Kubecost Engineering given the size of the patch.

**Comment by AndrewChubatiuk** [comment]
@AjayTripathy @mattray could you please assign this to someone as well as it's important to be merged together with #1430

**Comment by AndrewChubatiuk** [comment]
@mattray I'm just curious if there's anybody who can review it?

**Comment by mattray** [comment]
It's being discussed internally by Kubecost Engineering, I've asked them to bring the conversation back here.

**Comment by mattray** [comment]
Raised for review by Kubecost Engineering.

**Comment by zekker6** [comment]
Hi, a VictoriaMetrics contributor here. Is there anything that might help in reviewing of this PR from our side?
FYI: I've tested this PR recently with VictoriaMetrics components and it works just fine.

**Comment by AndrewChubatiuk** [comment]
@cliffcolvin any help needed?

**Comment by Momotoculteur** [comment]
Hey :) 

Thanks for you hard work @AndrewChubatiuk, and very excited to use OpenCost with VictoriaMetrics. Any roadmap about this pr to be merged in master ?  @cliffcolvin @mattray 

Bastien

**Comment by cliffcolvin** [comment]
> Hey :)
> 
> Thanks for you hard work @AndrewChubatiuk, and very excited to use OpenCost with VictoriaMetrics. Any roadmap about this pr to be merged in master ? @cliffcolvin @mattray
> 
> Bastien

@AndrewChubatiuk @Momotoculteur I will work to get this tested and merged next week. Thank you for the nudge here, I'll reach out if I run into any issues.

**Review by cliffcolvin — COMMENTED** [review]
LGTM

**Review by cliffcolvin — APPROVED** [review]

**Comment by cliffcolvin** [comment]
@AndrewChubatiuk this caused a downstream issue. I'll re-raise as soon as I can fix that. Will work on that today/this weekend to get this back in.

**Comment by omartheironman** [comment]
> @AndrewChubatiuk this caused a downstream issue. I'll re-raise as soon as I can fix that. Will work on that today/this weekend to get this back in.

@cliffcolvin just following up, has this been fixed?

**Comment by cliffcolvin** [comment]
@omartheironman and @AndrewChubatiuk I greatly appreciate your patience here, and apologize for my latency in response. I have had a few issues getting this resolved and tested. This is the top priority I have going into next week to get it across the line and merged back in. I will reach back out on Tuesday with an update, but should have it resolved by then.

**Comment by cliffcolvin** [comment]
> @omartheironman and @AndrewChubatiuk I greatly appreciate your patience here, and apologize for my latency in response. I have had a few issues getting this resolved and tested. This is the top priority I have going into next week to get it across the line and merged back in. I will reach back out on Tuesday with an update, but should have it resolved by then.

I am still doing some testing here. I have opened up #2407 to put this back in. I will keep digging on this tomorrow and send another update. Hoping that tomorrow's testing will complete this.

**Comment by cliffcolvin** [comment]
I had some higher priority work to complete right before holiday. I should be able to get this in and reviewed right after the first of the year when the team is back.

**Comment by dekhtyarev** [comment]
@cliffcolvin hi! 
Any chance of adding these changes to the next release?

**Comment by AjayTripathy** [comment]
Since these are merged they should be in the 2.1 release!

**Comment by AndrewChubatiuk** [comment]
@AjayTripathy this PR was reverted and reopened in #2407 without any further progress

**Comment by AjayTripathy** [comment]
Hi @AndrewChubatiuk apologies for the late response its looks like https://github.com/opencost/opencost/pull/2567 has more info

**Pull request merged**
