### PR TITLE
Add support for Open Telekom Cloud (OTC) provider

### LINKED ISSUE #2950: Add support for Open Telekom Cloud (OTC) provider
**Is your feature request related to a problem? Please describe.**
There is no support for Kubernetes Clusters running in Open Telekom Cloud (OTC).

**Describe the solution you'd like**
Implement an OTC provider that integrates the OTC pricing API [calculator.otc-service.com/en/open-telekom-price-api/](https://calculator.otc-service.com/en/open-telekom-price-api/). This will benefit OTC customers and increase OpenCost usage.

**Describe alternatives you've considered**
x

**Additional context**
x

### PR DESCRIPTION
**Pull request by pmaus22**
Signed-off-by: Philip Maus <philip.maus@d-velop.de>

## What does this PR change?
* Adds a new cloud service provider implementation for OTC. See https://www.open-telekom-cloud.com/en

## Does this PR relate to any other PRs?
* No

## How will this PR impact users?
* Users running clusters on OTC will be able to access pricing data.

## Does this PR address any GitHub or Zendesk issues?
* Closes https://github.com/opencost/opencost/issues/2950

## How was this PR tested?
* Tested on OTC with self-managed clusters

## Does this PR require changes to documentation?
* An informational section for the OTC provider should be added. Note that the OTC provider requires no additional configuration to function. See https://github.com/opencost/opencost-website/pull/309

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next OpenCost release? If not, why not?
* Release eligibility has not yet been determined.

### CODE REVIEW

**Comment by AjayTripathy** [comment]
Wow, so cool! Any chance you've got this running somewhere? We don't have the ability to spin up an OTC cluster on our end.

**Comment by pmaus22** [comment]
@AjayTripathy We are currently running it on our OTC and AWS Kubernetes clusters. The new code detects OTC as the cloud provider by checking whether the node label "cce.cloud.com/cce-nodepool" exists because OTC is not using a distinguishable ProviderID in the cluster properties.

**Comment by AjayTripathy** [comment]
Thank you! @cliffcolvin can we please review?

**Review by cliffcolvin — APPROVED** [review]

**Comment by cliffcolvin** [comment]
@pmaus22 thank you for this contribution merging now

**Pull request merged**
