### PR TITLE
use status/buildinfo endpoint to get status instead of status/config added variable to set static scrape interval

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**
- Use status/buildinfo endpoint instead of status/config to provide support for VictoriaMetrics
- Added KUBECOST_SCRAPE_INTERVAL env variable to make scrape interval discovery optional

## What does this PR change?
* alternative approach to #2407 to enable VM support

## Does this PR relate to any other PRs?
* #2407

## How will this PR impact users?
* 

## Does this PR address any GitHub or Zendesk issues?
* Closes ...

## How was this PR tested?
* 

## Does this PR require changes to documentation?
* 

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next OpenCost release? If not, why not?
*

### CODE REVIEW

**Comment by mattray** [comment]
@AndrewChubatiuk thanks, this looks useful to me. @opencost/opencost-maintainers anyone want to weigh in?

**Review by michaelmdresser — COMMENTED** [review]
This looks straightforward. What is the difference between `api.Config` and `api.Buildinfo`? Is there any meaningful difference when using Prometheus?

**Comment by AndrewChubatiuk** [comment]
@michaelmdresser VictoriaMetrics in a cluster mode has scrape config endpoint only on VMAgent component but to scrape metrics it should use VMSelect. It means that with a current approach to support VMAgent and VMSelect endpoints it's required to have two clients (which was introduced in #2407). To use a single client and keep it compatible with other Prometheus compatible solutions I've updated config endpoint (which is utilized to get a monitoring cluster status and scrape interval) to buildinfo and added ability to configure custom scrape interval manually

**Comment by michaelmdresser** [comment]
That makes sense to me. However, I'm trying to make sure that this does not break functionality when using Prometheus. Is there a meaningful difference between `api.Config` and `api.Buildinfo` when using Prometheus? Have you tested this PR by running it against a Prometheus instance in addition to VictoriaMetrics?

**Comment by AndrewChubatiuk** [comment]
yes, tested it with both prometheus and VM. there's no meaningful difference. left `api.Config` only in place, where it queries scrape interval, but the rest calls are just required to understand that prometheus is up and available.

**Review by michaelmdresser — APPROVED** [review]
OK, thanks for answering my questions

**Pull request merged**
