### PR TITLE
[Cache Optimization] Remove the k8s resource endpoints

### PR DESCRIPTION
**Pull request by mbolt35**
* Remove k8s resource endpoints proxied from opencost.

### CODE REVIEW

**Review by r2k1 — APPROVED** [review]
LGTM. But should it target develop branch instead?

**Comment by r2k1** [comment]
Maybe this one should be removed as well? Looks quite dangerous.


```
router.GET("/podLogs", a.GetPodLogs)
```

**Comment by mbolt35** [comment]
> Maybe this one should be removed as well? Looks quite dangerous.
> 
> ```
> router.GET("/podLogs", a.GetPodLogs)
> ```

Yes, good catch! Thank you

**Comment by mbolt35** [comment]
I'm targeting your branch because I have a matching changeset on our proprietary side to address the changes all at once. I'm going to hopefully detail an effort soon for some much broader changes to remove the downstream burden kubecost creates for opencost.

**Comment by r2k1** [comment]
Tbh, some other endpoints are potential security holes. It can flagged as a CVE with a high severity one day.

**Comment by mbolt35** [comment]
> Tbh, some other endpoints are potential security holes. It can flagged as a CVE with a high severity one day.

Let's get these called out and labeled. Tag @cliffcolvin as well so we can start mapping out a plan!

**Pull request merged**
