### PR TITLE
Update path in swagger.json

### PR DESCRIPTION
**Pull request by wuminorb**
## What does this PR change?
Document for API (swagger.json) 

## Does this PR relate to any other PRs?
no

## How will this PR impact users?
Correction of Information

## Does this PR address any GitHub or Zendesk issues?
no

## How was this PR tested?
Tested with curl

## Does this PR require changes to documentation?
Yes, only require documentation changes

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next OpenCost release? If not, why not?
No. I am not sure which release should include this PR

### CODE REVIEW

**Comment by AjayTripathy** [comment]
@nikovacevic aren't both endpoints valid?

**Comment by nikovacevic** [comment]
@AjayTripathy looks like we don't use the `/compute` endpoint any more: https://github.com/opencost/opencost/blob/develop/pkg/cmd/costmodel/costmodel.go#L53-L54

**Review by nikovacevic — APPROVED** [review]

**Comment by nikovacevic** [comment]
Well, wait. We do have another router here, with `/compute`: https://github.com/opencost/opencost/blob/develop/pkg/costmodel/router.go#L1738

**Comment by nikovacevic** [comment]
Okay, I can confirm that both are valid.

**Comment by AjayTripathy** [comment]
If both are valid should we really be removing one @nikovacevic ?

**Comment by nikovacevic** [comment]
To ask "should we remove one" indicates that we document both. We don't, though -- we only document the `/compute` endpoint, so the `/allocation` API is undocumented (but identical).

That said, we reference `/allocation/compute` elsewhere (e.g. in Postman docs) so it seems like, if we're only going to document one, then the `compute` version seems to be the one we want to keep.

(Ideally, we'll probably want to clean up, dedupe, and potentially version these APIs at some point, so that it's more clear what users should be using.)

**Comment by AjayTripathy** [comment]
@nikovacevic can we get this merged if you support the change? I don't think the quality gate is super relevant here.

**Comment by nikovacevic** [comment]
I originally approved, then revoked after I understood what was going on. I don't know what's right here. Which API do we want Opencost users to use, `/allocation` or `/allocation/compute`? They do the same thing.

Seems like the `swagger.json` is properly documented, already, and this PR can be closed -- but technically the docs can go either way.

**Comment by AjayTripathy** [comment]
@wuminorb any thoughts? Seems like both urls should work?

**Comment by cliffcolvin** [comment]
> @wuminorb any thoughts? Seems like both urls should work?

@AjayTripathy we haven't heard back here, thoughts on moving this forward?

**Comment by wuminorb** [comment]
hi @AjayTripathy @nikovacevic and @cliffcolvin , sorry, I forgot this PR. 

As `/allocation` is the endpoint that shown in document. And it's also more simple and straight forward. `/allocation/compute` may kind of confusion as storage/network costs also included. My suggestions is that we can use `/allocation` in document and swagger ui. And maybe we can keep the router for now, add some comments/annotation to tell people this is deprecated,  in case someone is using `/allocation/compute`. What do you think?

**Comment by cliffcolvin** [comment]
I agree, working on merging. Thanks for the contribution here @wuminorb, will get this merged quickly.

**Pull request merged**
