### PR TITLE
feat: allow adding prefix to prometheus query

### PR DESCRIPTION
**Pull request by alileza**
## What does this PR change?
* Adding support for configuring prefix for prometheus metric 

## Does this PR relate to any other PRs?
* nope

## How will this PR impact users?
* there shouldn't be any behaviour changes unless the env var is set

## How was this PR tested?
* run it locally with both prometheus and opencost running

## Does this PR require changes to documentation?
* probably? a new feature

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next OpenCost release? If not, why not?
*

### CODE REVIEW

**Comment by AjayTripathy** [comment]
This feels like a pretty major change, can you share a little bit more about the motivation for this change?

**Comment by alileza** [comment]
@AjayTripathy I wonder why you think it's major changes? there should be no effects unless your apply the env var. 

The issue simply in our orgs we segregate metrics per it's namespace, so we added `opencost_` prefix for all opencost /metrics endpoint. And it causing opencost didn't work as expected, because it still trying to query from those named metrics without `opencost_` prefix.

Also some of opencost expose metrics collide with kube-state-metrics, which this could help separate them as well

**Comment by mattray** [comment]
Thanks for the PR, it is quite a substantial change so I'm looping in other @opencost/opencost-maintainers  for feedback

**Comment by nikovacevic** [comment]
Seems like we first need to decide if this is a valid goal, or not. To inform that decision, we might explore whether this metric re-naming practice is a best practice, or something to be avoided in favor of keeping the original metric names. Who makes that call?

After we have that answer, I can take a pass and review whether or not this is implemented appropriately, which should be more-or-less straightforward (though admittedly very delicate).

**Pull request closed without merging**
