### PR TITLE
Removed IsThanosEnabled check

### PR DESCRIPTION
**Pull request by jcharcalla**
Removed 'IsThanosEnabled' check as it is not required and possibly causing issues for some users.

Signed-off-by: Jason Charcalla <jason@kubecost.com>

## What does this PR change?
* It removes code that checks if thanos is enabled, and if not sets ETLResolutionSeconds to 1 min.

## Does this PR address any GitHub or Zendesk issues?
* [ZD: 3246](https://kubecost.zendesk.com/agent/tickets/3246)

## How was this PR tested?
* It was not tested

### CODE REVIEW

**Comment by jcharcalla** [comment]
@AjayTripathy Here is the PR we discussed on todays call.

**Comment by AjayTripathy** [comment]
We still need GetETLResolution, it's just the if statement that needs deletion.

**Comment by jcharcalla** [comment]
Makes sense, I've updated it.

**Comment by AjayTripathy** [comment]
@nikovacevic seems like a quick one, wdyt? I don't know why we ever set this to 1m

**Review by nikovacevic — APPROVED** [review]

**Comment by nikovacevic** [comment]
Seems fine to me! Thank you @jcharcalla

**Pull request merged**
