### PR TITLE
use `policy/v1` for `PodDisruptionBudget`

### PR DESCRIPTION
**Pull request by a7i**
## What does this PR change?
* uses policy/v1 for listing PDBs

## Does this PR relate to any other PRs?
* No

## How will this PR impact users?
* policy/v1beta1 is no longer served as of 1.25

## Does this PR address any GitHub or Zendesk issues?
* Closes ...

## How was this PR tested?
* 

## Does this PR require changes to documentation?
* 

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next OpenCost release? If not, why not?
*

### CODE REVIEW

**Comment by mattray** [comment]
@a7i thanks for opening this! Looking at the [Kubernetes API documentation](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125) I see this API was removed in 1.25 and available since 1.21. This means we should update 
https://www.opencost.io/docs/installation/install
and Kubecost should update
https://docs.kubecost.com/install-and-configure/install/environment#supported-kubernetes-versions
accordingly.

**Review by mattray — APPROVED** [review]
I want another @opencost/opencost-maintainers to merge it, but it looks good to me.

**Review by michaelmdresser — APPROVED** [review]
If I'm reading K8s notes correctly, `policy/v1` `PodDisruptionBudget` was added in K8s v1.21 (https://github.com/kubernetes/sig-release/blob/master/releases/release-1.21/release-notes/release-notes-draft.md). I think that's enough prior versions of support for us to roll forward with only supporting policy/v1 PDBs.

EDIT: Matt, I can't read. Thank you for doing the research.

**Comment by michaelmdresser** [comment]
Hey @AjayTripathy -- heads up that this will bump KC's min K8s version from v1.20 to v1.21, but I think it might only affect Spot Commander.

**Pull request merged**
