### PR TITLE
Update CloudCost service categorization for AWS

### PR DESCRIPTION
**Pull request by thomasvn**
## What does this PR change?
* Update CloudCost service categorization for AWS. GuardDuty should not be classified as "Compute", but instead as "Other".

## Does this PR relate to any other PRs?
* N/A

## How will this PR impact users?
* Fixes categorization of an AWS resource for the CloudCost API.
* For downstream apps (e.g. Kubecost), this also fixes the cost reconciliation process.

## Does this PR address any GitHub or Zendesk issues?
* N/A

## How was this PR tested?

Enabled AmazonGuardDuty in one of my environments (it's on a free trial, but still shows up in the CUR with a $0 charge).

Before this change, notice that AmazonGuardDuty was being categorized as "Compute" when it had a ProviderId of `i-*`. There are also cases when other AmazonGuardDuty services are categorized as "Network" or "Other" likely due to other columns in the CUR. Details here. [guardduty-cloudcost.txt](https://github.com/opencost/opencost/files/15180102/guardduty-cloudcost.txt)

After this change, all AmazonGuardDuty which has a ProviderID of `i-*` are now categorized as "Other". Even though runtime monitoring is being performed for each individual EC2 instance, we do not want to merge these costs into the cost of a node (which should solely be CPU + RAM + GPU). Details here. [guardduty-cloudcost-customimage.txt](https://github.com/opencost/opencost/files/15180119/guardduty-cloudcost-customimage.txt)

## Does this PR require changes to documentation?
* N/A

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next OpenCost release? If not, why not?
*

### CODE REVIEW

**Review by michaelmdresser — COMMENTED** [review]
Conceptually LGTM but I'd like to see the results of a test before approving

**Comment by ameijer** [comment]
@thomasvn , any other context information we can possibly use? trying to use a check on 'is guard duty' if possible

**Comment by thomasvn** [comment]
@ameijer Not seeing anything else we could use to validate the service is `AmazonGuardDuty`. It seems the existing code mostly checks the `Service` name to determine its category:

https://github.com/opencost/opencost/blob/540b35727c6cb120aab07ad20d10ffe7e619d5ca/pkg/cloud/aws/athenaquerier.go#L218-L234

And it seems `Service` name is derived from this column of the CUR:

https://github.com/opencost/opencost/blob/540b35727c6cb120aab07ad20d10ffe7e619d5ca/pkg/cloud/aws/athenaintegration.go#L354

**Comment by ameijer** [comment]
OK @thomasvn , after reviewing the code you linked, I think your approach is solid and in line with our existing approach. Would also love to see a live test as per @michaelmdresser 's request

**Comment by AjayTripathy** [comment]
Are there services other than GuardDuty that target nodes? Should we not do the inverse and whitelist rows that are used for pricing instead of blacklisting GuardDuty? I am ok with a temporary fix here but we should think about future-proofing.

**Comment by thomasvn** [comment]
> Are there services other than GuardDuty that target nodes?

@AjayTripathy Not that I know of, but it's certainly possible.

> Should we not do the inverse and whitelist rows that are used for pricing instead of blacklisting GuardDuty? I am ok with a temporary fix here but we should think about future-proofing.

This is something we considered, but we would need to be very confident that we have coverage of all the different `Service` names which would be considered Compute. Would definitely require a bit more rigorous testing. I'm open to doing this though! Change would look like:

```go
	if strings.HasPrefix(providerID, "i-") && strings.ToUpper(service) == "AMAZONEC2" {
		return opencost.ComputeCategory
	}
```

**Comment by AjayTripathy** [comment]
Ok. Let's start with the p0 fix (blacklisting guardduty) which is the known issue, but file an issue to handle via whitelist and get that appropriately tested?

**Review by Sean-Holcomb — COMMENTED** [review]
This looks good to me, my only question is if we can't just put this if above the if it is nested in. Are there providerId with "vol-" and service guard duty that we want classified as storage?

**Comment by thomasvn** [comment]
@Sean-Holcomb I'm still currently testing in our environment, but I don't believe there is ever `Service=AmazonGuardDuty` and `ProviderID=vol-*`.

**Comment by thomasvn** [comment]
@ameijer @Sean-Holcomb I've tested the following change in one of my environments. Details in the PR notes above. Let me know what you think and if we are good to approve/merge!

**Review by ameijer — APPROVED** [review]
thomas I reviewed the tests and it LGTM, sean is FTO today so @cliffcolvin might need to merge for us

**Review by Sean-Holcomb — APPROVED** [review]

**Pull request merged**
