### PR TITLE
Revert "Revert "added a separate client for prometheus scrape config endpoint""

### PR DESCRIPTION
**Pull request by cliffcolvin**
Reverts opencost/opencost#2316

We temporarily reverted this change to accommodate time to fix downstream issues with this change. I am un-reverting this now to test and merge this.

### CODE REVIEW

**Comment by bighiro** [comment]
@cliffcolvin Just to follow up on this PR, can you let me know when this PR will get merged..

**Comment by cliffcolvin** [comment]
> @cliffcolvin Just to follow up on this PR, can you let me know when this PR will get merged..
I had some higher priority work to complete right before holiday. I should be able to get this in and reviewed right after the first of the year when the team is back.

**Comment by AndrewChubatiuk** [comment]
@cliffcolvin any updates on this feature?

**Comment by cliffcolvin** [comment]
> @cliffcolvin any updates on this feature?

I've pulled this back in to try and get it across the line. I am updating based on several refactors and testing. Will update with ETA.

**Comment by mbolt35** [comment]
This change feels a bit over the top for what it's trying to accomplish. 

1) It seems very odd that we require two separate prometheus clients, where one of them is simply used to get scrape configs. 
2) This makes many changes to the `env` package that all feel like complete hacks. 

I have no problem with a single flag that allows us to direct a specific request to a different endpoint for getting the Config, but that requirement doesn't justify modifying any of the code this change modifies. 

If my understanding of this change is incorrect, I would love more information. Why are multiple prometheus clients required?

**Comment by cliffcolvin** [comment]
> This change feels a bit over the top for what it's trying to accomplish.
> 
> 1. It seems very odd that we require two separate prometheus clients, where one of them is simply used to get scrape configs.
> 2. This makes many changes to the `env` package that all feel like complete hacks.
> 
> I have no problem with a single flag that allows us to direct a specific request to a different endpoint for getting the Config, but that requirement doesn't justify modifying any of the code this change modifies.
> 
> If my understanding of this change is incorrect, I would love more information. Why are multiple prometheus clients required?

@AndrewChubatiuk can you help fill in some color here? It causes a lot of downstream churn and we'd like to simplify this.

**Comment by AndrewChubatiuk** [comment]
I would like to simplify, but prometheus client is utilized to:
 - get scrape config
 - get metrics
 problem is that for VictoriaMetrics scrape config and metrics are available on different services (VMAgent and VictoriaMetrics)

**Comment by AndrewChubatiuk** [comment]
I would like to simplify, but prometheus client is utilized to:
 - get scrape config
 - get metrics
 
 problem is that for VictoriaMetrics scrape config and metrics are available on different services (VMAgent and VictoriaMetrics)
 @mbol35 if we can make request to scrape config optional, we can use a single client for VM

**Comment by AndrewChubatiuk** [comment]
@cliffcolvin @mbolt35 
[here](https://github.com/opencost/opencost/pull/2567) is a smaller PR, which also enables VM support

**Comment by cliffcolvin** [comment]
@AndrewChubatiuk thanks, I'll sync with @mbolt35 in the morning on the new pr and discuss!

**Comment by cliffcolvin** [comment]
> @cliffcolvin @mbolt35 [here](https://github.com/opencost/opencost/pull/2567) is a smaller PR, which also enables VM support

@AndrewChubatiuk I have asked for some feedback from our engineering team to get eyes on the PR. I'm closing this one for now and we'll have the conversation in https://github.com/opencost/opencost/pull/2567

**Comment by mbolt35** [comment]
> @mbol35 if we can make request to scrape config optional, we can use a single client for VM

@AndrewChubatiuk Does https://github.com/opencost/opencost/pull/2567 meet your needs (I actually just noticed this was closed)? I totally support the alternative change set - thank you very much for working with us on this. Apologies for the many delays. Thanks again for the contribution!

If this doesn't fully resolve your needs, let us know.

**Pull request closed without merging**
