### PR TITLE
Cloud Cost UI goes blank with no cloud-integration.json as a secret

### LINKED ISSUE #2284: Cloud Cost UI goes blank with no cloud-integration.json as a secret
If you click on the `Cloud Costs` tab in the UI and their is no secret with the cloud-integration.json, the page goes completely blank. No navigation, no header, just a white page. There's no error message in the logging either.

The expectation is that it should render the page with a message along the lines of "There are no Cloud Cost integrations currently configured." and hopefully there would be an error message in the opencost container logs that the request was made but there's no configuration available.

### PR DESCRIPTION
**Pull request by jjarrett21**
## What does this PR change?
* Checks for cloud cost status

## Does this PR relate to any other PRs?
* no

## How will this PR impact users?
* should show an error message and a docs link if they don't have cloud cost enabled 

## Does this PR address any GitHub or Zendesk issues?
* Closes #2284 

## How was this PR tested?
* self

## Does this PR require changes to documentation?
* no but the included docs link is wrong and @mattray will need to provide the correct one.

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next OpenCost release? If not, why not?
* 
Screenshot 2023-11-03 at 11 46 34 PM

### CODE REVIEW

**Comment by jjarrett21** [comment]
Updated the styles to be a bit more consistent with what we have previously

**Comment by dwbrown2** [comment]
Would it be easy to remove the upper error box? If so, like that change?

image

**Comment by jjarrett21** [comment]
@dwbrown2 changed it so that it should only show one or the other.

**Comment by dwbrown2** [comment]
@jjarrett21 I'm just seeing the error message now, should we instead expect to see the "no cloud integration" message?

image

**Comment by jjarrett21** [comment]
how bout now?

**Comment by dwbrown2** [comment]
I'm not seeing anything in preview: https://opencost-qbpimiolx-kubecost.vercel.app/

Have a screenshot?

**Comment by jjarrett21** [comment]
Screenshot 2023-11-09 at 3 57 38 PM
@dwbrown2 😅

**Comment by dwbrown2** [comment]
Haven't reviewed code, but this looks good to me! 

This isn't the right docs page though, we want to use an OpenCost page: https://docs.kubecost.com/using-kubecost/navigating-the-kubecost-ui/cloud-costs-explorer#installation-and-configuration

Nit: I might also open the docs link in a new window.

**Comment by jjarrett21** [comment]
done and done

**Comment by dwbrown2** [comment]
I'm still seeing kubecost docs referenced in code, but once that's done I think the UX is good! Would be great to get a maintainer review when ready.

**Comment by jjarrett21** [comment]
Oh @dwbrown2 I was moving fast and I thought the link you posted was the open cost one lol. I'll ask @mattray for the proper docs link

**Comment by dwbrown2** [comment]
I know @mattray is likely out for the weekend, so sharing this in case helpful: https://www.opencost.io/docs/configuration/#cloud-costs

We may want to change/improve but this at least feels like a fine starting point.

**Review by mattray — APPROVED** [review]
Tested locally

**Pull request merged**
